const $ = s => document.querySelector(s);
const view = $('#view');
const toast = $('#toast');
const modalHost = $('#modalHost');
const importFile = $('#importFile');
const fmt = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0));
const pct = n => `${Number(n||0).toFixed(1).replace('.',',')}%`;
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : Date.now()+Math.random().toString(16).slice(2));
const isoToday = () => {const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const nowIso = () => new Date().toISOString();
const brDate = iso => iso ? new Date(iso+'T12:00:00').toLocaleDateString('pt-BR') : '—';
const todayBR = () => new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date());
const num = raw => {
  if(typeof raw==='number') return raw;
  const s=String(raw??'').trim().replace(/\s/g,'').replace(/R\$/gi,'');
  if(!s) return 0;
  if(s.includes(',') && s.includes('.')) return Number(s.replace(/\./g,'').replace(',','.'))||0;
  if(s.includes(',')) return Number(s.replace(',','.'))||0;
  return Number(s)||0;
};
const escapeHtml = s => String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const userInitials = name => {const parts=String(name||'Usuário').trim().split(/\s+/).filter(Boolean);return ((parts[0]?.[0]||'U')+(parts.length>1?(parts[parts.length-1]?.[0]||''):'' )).toUpperCase().slice(0,2)};

const seedData = {
  // O repositório GitHub Pages é público. A aplicação não distribui nenhum
  // dado financeiro pessoal no código-fonte; uma instalação nova começa vazia
  // e recebe a base real somente após o usuário conectar/sincronizar seu Drive.
  transactions:[], goals:[], accounts:[], investments:[], debts:[], recurring:[], cards:[],
  cardPurchases:[], installments:[],
  budget:{
    'Alimentação':0,'Transporte':0,'Lazer':0,'Saúde':0,'Educação':0,'Contas e serviços':0,'Outros':0
  },
  reserve:{current:0,months:6},
  settings:{monthlyIncome:0,essentialBase:0,userName:'Usuário',theme:'light',autosave:true},
  importedFiles:[], scenarios:[]
};

function defaultState(){return {meta:{app:'Controle Financeiro Mobile',version:'0.8.0',user:'Usuário',deviceId:`mobile-${uid().slice(0,8)}`,createdAt:nowIso(),updatedAt:nowIso(),lastSyncAt:null,syncProvider:'Google Drive',syncReady:true,syncConnected:false,pendingChanges:0,changeQueue:[],googleClientId:'',driveFolderId:'',driveFileId:'',driveLastRevision:0,driveLastHash:'',driveLastLocalHash:'',driveLastRemoteHash:'',driveLastModified:'',autoSyncEnabled:true,autoSyncIntervalSec:60,autoSyncConflict:false,autoSyncLastError:'',autoSyncLastAttempt:null},data:JSON.parse(JSON.stringify(seedData))}}
function ensureData(d){
  const defaults=JSON.parse(JSON.stringify(seedData));
  d=(d&&typeof d==='object')?d:{};
  const arrayKeys=['transactions','goals','accounts','investments','debts','recurring','cards','cardPurchases','installments','importedFiles','scenarios'];
  for(const k of arrayKeys) if(!Array.isArray(d[k])) d[k]=[];
  d.budget=(d.budget&&typeof d.budget==='object'&&!Array.isArray(d.budget))?d.budget:{...defaults.budget};
  d.reserve={...defaults.reserve,...((d.reserve&&typeof d.reserve==='object')?d.reserve:{})};
  d.settings={...defaults.settings,...((d.settings&&typeof d.settings==='object')?d.settings:{})};
  d.investments=d.investments.map(x=>({invested:x.invested??x.value??0,current:x.current??x.value??0,kind:x.kind??'Investimento',history:Array.isArray(x.history)?x.history:[],incomeHistory:Array.isArray(x.incomeHistory)?x.incomeHistory:[],...x}));
  d.goals=d.goals.map(x=>({...x,history:Array.isArray(x.history)?x.history:[]}));
  d.debts=d.debts.map(x=>({...x,payments:Array.isArray(x.payments)?x.payments:[]}));
  return d;
}
function migrate(raw){if(!raw)return defaultState(); if(raw.meta&&raw.data){const def=defaultState();raw.data=ensureData(raw.data);raw.meta={...def.meta,...raw.meta,version:'0.8.0'};return raw} const st=defaultState();st.data=ensureData(raw);return st}
const store={get(){try{return migrate(JSON.parse(localStorage.getItem('financeiro_mobile_state')))}catch{return defaultState()}},set(v){localStorage.setItem('financeiro_mobile_state',JSON.stringify(v))},reset(){localStorage.removeItem('financeiro_mobile_state');location.reload()}};
let state=store.get(),data=state.data,currentRoute='home',deferredPrompt=null;
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast._t);showToast._t=setTimeout(()=>toast.classList.remove('show'),2200)}
function save(){state.data=data;state.meta.updatedAt=nowIso();state.meta.pendingChanges=state.meta.changeQueue.length;store.set(state)}
function queueChange(type,summary,schedule=true){state.meta.changeQueue.unshift({id:uid(),type,summary,at:nowIso(),deviceId:state.meta.deviceId});state.meta.changeQueue=state.meta.changeQueue.slice(0,100);save();if(schedule)scheduleAutoDriveSync(3500)}
function nav(route){currentRoute=route;if(location.hash)history.replaceState(null,'',location.pathname);render()}
function openModal(content){modalHost.innerHTML=`<div class="sheet">${content}</div>`;modalHost.classList.remove('hidden')}
function closeModal(){modalHost.classList.add('hidden');modalHost.innerHTML=''}
modalHost.addEventListener('click',e=>{if(e.target===modalHost)closeModal()});
function latestPeriod(){
  const d=new Date();
  return {year:d.getFullYear(),month:d.getMonth()+1};
}
function inPeriod(tx,year,month){
  if(!tx?.date)return false;
  return Number(tx.date.slice(0,4))===Number(year)&&Number(tx.date.slice(5,7))===Number(month);
}
function flowTotals(year,month){
  let income=0,expense=0,investmentContrib=0,withdrawals=0;
  for(const x of (data.transactions||[])){
    if(!inPeriod(x,year,month))continue;
    if(x.ownTransfer===true||x.ownTransfer===1)continue;
    const amount=Math.abs(Number(x.amount||0));
    if(x.type==='expense'&&x.category==='Investimentos'){investmentContrib+=amount;continue;}
    if(x.type==='income'&&x.category==='Resgate de investimento'){withdrawals+=amount;continue;}
    if(x.type==='income')income+=amount;
    else if(x.type==='expense'&&x.impactBudget!==false&&x.impactBudget!==0)expense+=amount;
  }
  return {income,expense,balance:income-expense,investmentContrib,withdrawals};
}
function totals(){
  const period=latestPeriod(),flow=flowTotals(period.year,period.month);
  const accounts=data.accounts.filter(x=>x.include!==false).reduce((a,b)=>a+Number(b.balance||0),0);
  const investments=data.investments.reduce((a,b)=>a+Number(b.current||0),0);
  const debts=data.debts.reduce((a,b)=>a+Number(b.balance||0),0);
  return {...flow,accounts,investments,debts,networth:accounts+investments-debts,period};
}
function budgetTotal(){return Object.values(data.budget).reduce((a,b)=>a+Number(b||0),0)}
function monthlyRecurring(){return data.recurring.filter(x=>x.active).reduce((a,b)=>a+(x.frequency==='Mensal'?x.amount:x.frequency==='Semanal'?x.amount*4.33:x.amount/12),0)}
function reserveSummary(){const base=data.settings.essentialBase||monthlyRecurring()||0,target=base*(data.reserve.months||6),current=data.reserve.current||0;return{base,target,current,missing:Math.max(0,target-current),progress:target?current/target*100:0}}
function healthSummary(){const t=totals(),r=reserveSummary(),income=data.settings.monthlyIncome||t.income||1,debtMonthly=data.debts.reduce((a,b)=>a+(b.payment||0),0),saveRate=Math.max(0,(income-t.expense)/income*100),debtCommit=debtMonthly/income*100,reserveMonths=r.base?r.current/r.base:0;let score=50+Math.min(20,saveRate*.7)+Math.min(20,reserveMonths*4)-Math.min(25,debtCommit*.8);score=Math.max(0,Math.min(100,score));return{score,saveRate,debtCommit,reserveMonths,networth:t.networth}}
function categorySpent(cat){const p=latestPeriod();return data.transactions.filter(x=>inPeriod(x,p.year,p.month)&&x.type==='expense'&&x.category===cat&&x.category!=='Investimentos'&&x.ownTransfer!==true&&x.ownTransfer!==1&&x.impactBudget!==false&&x.impactBudget!==0).reduce((a,b)=>a+Number(b.amount||0),0)}
function progressPct(g){return Math.min(100,Math.round((g.current/g.target)*100||0))}
function sectionHead(title,action=''){return `<div class="page-head"><div class="page-title">${title}</div>${action}</div>`}

function home(){const t=totals(),bt=budgetTotal(),bp=Math.min(100,Math.round(t.expense/(bt||1)*100));return `<section><div class="hero-greeting">Olá, ${escapeHtml(data.settings.userName.split(' ')[0]||'Usuário')} 👋</div><div class="date-line">${todayBR()}</div><div class="card sync-card" onclick="nav('sync')"><div class="drive-icon">▲</div><div style="flex:1"><div class="row-between"><div><div class="sync-title">${state.meta.syncConnected?'Google Drive sincronizado':'Google Drive não conectado'}</div><div class="sync-sub"><span class="dot"></span>${state.meta.syncConnected?'Sincronização automática entre PC e celular':'Abra a Central de sincronização para conectar'}</div></div><span class="chip blue">${state.meta.pendingChanges} pend.</span></div></div></div><div class="card balance-card"><div class="balance-label">Saldo das movimentações</div><div class="balance-value">${fmt(t.balance)}</div><div class="balance-note"><strong>●</strong> dados salvos neste aparelho</div><div class="mini-stats"><div class="mini-pill">Patrimônio ${fmt(t.networth)}</div><div class="mini-pill">Dívidas ${fmt(t.debts)}</div></div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Receitas</div><div class="kpi-value">${fmt(t.income)}</div></div><div class="kpi red"><div class="kpi-label">Gastos</div><div class="kpi-value">${fmt(t.expense)}</div></div></div><div class="card"><div class="section-title">Ações rápidas</div><div class="quick-actions"><button class="quick" onclick="openNewTransaction()"><div class="qicon">⇄</div><small>Movimentar</small></button><button class="quick" onclick="nav('goals')"><div class="qicon">◎</div><small>Metas</small></button><button class="quick" onclick="nav('cards')"><div class="qicon">▣</div><small>Cartões</small></button><button class="quick" onclick="nav('investments')"><div class="qicon">▥</div><small>Investimentos</small></button></div></div><div class="card"><div class="row-between"><div><div class="section-title">Resumo do mês</div><div class="muted small">Transferências próprias e aportes não entram em Receitas/Gastos</div></div><div class="muted small">Orçamento ${fmt(bt)}</div></div><div class="progress ${bp>=90?'yellow':'blue'}"><div style="width:${bp}%"></div></div><div style="margin-top:9px"><strong>${bp}%</strong> <span class="muted">do orçamento utilizado</span></div><div class="small muted">${fmt(t.expense)} de ${fmt(bt)}</div></div><div class="card"><div class="row-between"><div class="section-title">Saúde financeira</div><button class="link-btn" onclick="nav('health')">Ver detalhes</button></div>${healthCard()}</div></section>`}
function healthCard(){const h=healthSummary();return `<div class="row-between"><div><div style="font-size:34px;font-weight:900;color:${h.score>=75?'var(--green)':h.score>=50?'var(--yellow)':'var(--red)'}">${Math.round(h.score)}/100</div><div class="muted small">Pontuação estimada</div></div><span class="chip ${h.score>=75?'green':h.score>=50?'yellow':'blue'}">Reserva ${h.reserveMonths.toFixed(1).replace('.',',')} meses</span></div>`}

function groupedTransactions(list){const groups={};list.forEach(x=>(groups[x.date]??=[]).push(x));return Object.keys(groups).sort().reverse().map(date=>`<div class="tx-group-title">${date===isoToday()?'Hoje':brDate(date)}</div><div class="card">${groups[date].map(tx=>`<div class="tx" onclick="openTxActions('${tx.id}')"><div class="tx-icon">${tx.icon||'•'}</div><div><div class="tx-title">${escapeHtml(tx.description)}</div><div class="tx-sub">${escapeHtml(tx.category)} • ${escapeHtml(tx.account||'Conta')}</div></div><div><div class="tx-amount ${tx.type==='income'?'income':'expense'}">${tx.type==='income'?'+ ':'- '}${fmt(tx.amount)}</div><div class="tx-time">${tx.time||''}</div></div></div>`).join('')}</div>`).join('')}
function transactions(){return `${sectionHead('Movimentações','<button class="secondary" onclick="nav(\'import\')">Importar</button>')}<div class="segment" id="txSeg"><button class="active" data-filter="all">Todas</button><button data-filter="income">Receitas</button><button data-filter="expense">Despesas</button></div><input id="txSearch" class="search" placeholder="Buscar movimentações..."/><div id="txList">${groupedTransactions(data.transactions)}</div><button class="fab" onclick="openNewTransaction()">+</button>`}
function bindTransactions(){const buttons=[...document.querySelectorAll('#txSeg button')],search=$('#txSearch');function apply(){const f=document.querySelector('#txSeg button.active').dataset.filter,q=(search.value||'').toLowerCase(),list=data.transactions.filter(x=>(f==='all'||x.type===f)&&`${x.description} ${x.category} ${x.account||''}`.toLowerCase().includes(q));$('#txList').innerHTML=list.length?groupedTransactions(list):'<div class="empty">Nenhuma movimentação encontrada.</div>'}buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');apply()});search.oninput=apply}
function openNewTransaction(){currentRoute='newtx';render()}
function newTransaction(){return `${sectionHead('Nova Movimentação','')}<div class="card form-card"><div class="segment" id="typeSeg"><button class="active" data-type="expense">Despesa</button><button data-type="income">Receita</button></div><label>Valor</label><input id="txAmount" class="field money-field" inputmode="decimal" placeholder="R$ 0,00"/><label>Categoria</label><select id="txCategory" class="field">${Object.keys(data.budget).map(c=>`<option>${escapeHtml(c)}</option>`).join('')}<option>Trabalho</option><option>Investimentos</option><option>Resgate de investimento</option><option>Transferência entre contas</option></select><label>Descrição</label><input id="txDescription" class="field" placeholder="Ex.: Mercado, combustível, salário..."/><label>Data</label><input id="txDate" type="date" class="field" value="${isoToday()}"/><label>Conta</label><select id="txAccount" class="field">${data.accounts.map(a=>`<option>${escapeHtml(a.name)}</option>`).join('')}</select><label>Impacta orçamento?</label><select id="txImpact" class="field"><option value="1">Sim</option><option value="0">Não</option></select><label>É transferência entre minhas contas?</label><select id="txOwnTransfer" class="field"><option value="0">Não</option><option value="1">Sim</option></select><button class="primary" onclick="saveTransaction()">Salvar movimentação</button></div>`}
function bindTypeSeg(){document.querySelectorAll('#typeSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#typeSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function saveTransaction(){const amount=num($('#txAmount').value),desc=$('#txDescription').value.trim();if(!amount||!desc)return showToast('Informe valor e descrição');const type=document.querySelector('#typeSeg button.active').dataset.type,ownTransfer=$('#txOwnTransfer')?.value==='1',category=$('#txCategory').value;data.transactions.unshift({id:uid(),date:$('#txDate').value||isoToday(),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),type,amount,category,description:desc,account:$('#txAccount').value,impactBudget:ownTransfer?false:$('#txImpact')?.value!=='0',ownTransfer,icon:type==='income'?'💼':'🧾'});queueChange('transaction',`${type==='income'?'Receita':'Despesa'} ${fmt(amount)}`);showToast('Movimentação salva');nav('transactions')}
function openTxActions(id){const x=data.transactions.find(t=>t.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(x.description)}</div><div class="sheet-sub">${brDate(x.date)} • ${escapeHtml(x.category)} • ${fmt(x.amount)}</div><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Fechar</button><button class="primary danger-btn" onclick="deleteTransaction('${id}')">Excluir</button></div>`)}
function deleteTransaction(id){data.transactions=data.transactions.filter(x=>x.id!==id);queueChange('transaction_deleted','Movimentação excluída');closeModal();render()}

function goals(){const r=reserveSummary();return `${sectionHead('Metas & reserva','<button class="circle-add" onclick="openNewGoal()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Reserva de emergência</div><div class="muted small">${fmt(r.current)} de ${fmt(r.target)} • ${data.reserve.months} meses</div></div><button class="secondary" onclick="openReserve()">Atualizar</button></div><div class="progress" style="margin-top:10px"><div style="width:${Math.min(100,r.progress)}%"></div></div><div class="small muted" style="margin-top:6px">Faltam ${fmt(r.missing)}</div></div><div class="segment" id="goalSeg"><button class="active" data-goal-filter="all">Todas</button><button data-goal-filter="open">Em andamento</button><button data-goal-filter="done">Concluídas</button></div><div id="goalList">${goalCards(data.goals)}</div>`}
function goalCards(list){return list.length?list.map(g=>{const p=progressPct(g);return `<div class="card goal-card" onclick="openGoal('${g.id}')"><div class="goal-top"><div class="goal-icon">${g.icon||'🎯'}</div><div><div class="goal-name">${escapeHtml(g.name)}</div><div class="goal-money"><strong>${fmt(g.current)}</strong> de ${fmt(g.target)}</div></div><span class="chip ${p>=100?'green':'blue'}">${p}%</span></div><div class="goal-bottom"><div class="progress"><div style="width:${p}%"></div></div><div class="pct">${p}%</div></div><div class="goal-meta"><span>Faltam <strong>${fmt(Math.max(0,g.target-g.current))}</strong></span><span>${brDate(g.deadline)}</span></div></div>`}).join(''):'<div class="empty">Nenhuma meta.</div>'}
function bindGoals(){document.querySelectorAll('#goalSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#goalSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.goalFilter,l=data.goals.filter(g=>f==='all'||(f==='done'?g.current>=g.target:g.current<g.target));$('#goalList').innerHTML=goalCards(l)})}
function openGoal(id){currentRoute='goaldetail';location.hash=`#/goaldetail/${id}`;render()}
function goalDetail(){const id=location.hash.split('/')[2],g=data.goals.find(x=>x.id===id)||data.goals[0];if(!g)return `${sectionHead('Detalhe da Meta','')}<div class="empty">Meta não encontrada. <button class="link-btn" onclick="nav('goals')">Voltar para metas</button></div>`;const p=progressPct(g);return `${sectionHead('Detalhe da Meta','<button class="secondary danger" onclick="deleteGoal(\''+g.id+'\')">Apagar</button>')}<div class="card"><div class="goal-top"><div class="goal-icon">${g.icon||'🎯'}</div><div><div class="goal-name">${escapeHtml(g.name)}</div><div class="tx-sub">${escapeHtml(g.note||g.type||'Objetivo financeiro')}</div></div><span class="chip ${p>=100?'green':'blue'}">${p>=100?'Concluída':'Em andamento'}</span></div><div class="detail-kpis" style="margin-top:15px"><div class="mini-kpi"><small>Valor da meta</small><strong>${fmt(g.target)}</strong></div><div class="mini-kpi"><small>Guardado</small><strong>${fmt(g.current)}</strong></div><div class="mini-kpi"><small>Falta</small><strong>${fmt(Math.max(0,g.target-g.current))}</strong></div></div><div class="progress" style="margin-top:16px"><div style="width:${p}%"></div></div></div><div class="card"><div class="row-between"><div class="section-title">Histórico de aportes</div><button class="secondary" onclick="openGoalContribution('${g.id}')">+ Adicionar</button></div>${(g.history||[]).map(h=>`<div class="tx"><div class="tx-icon" style="background:var(--greenSoft);color:var(--green)">↗</div><div><div class="tx-title">${escapeHtml(h.note||'Aporte')}</div><div class="tx-sub">${brDate(h.date)}</div></div><div class="tx-amount income">+ ${fmt(h.amount)}</div></div>`).join('')||'<div class="empty">Nenhum aporte registrado.</div>'}</div>`}
function openGoalContribution(id){const g=data.goals.find(x=>x.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">Adicionar valor</div><div class="sheet-sub">${escapeHtml(g.name)} • Guardado ${fmt(g.current)} de ${fmt(g.target)}</div><label>Valor do aporte</label><input id="goalAmount" class="field money-field" inputmode="decimal" placeholder="R$ 0,00"/><label>Observação</label><input id="goalNote" class="field" placeholder="Ex.: aporte semanal"/><label>Data</label><input id="goalDate" type="date" class="field" value="${isoToday()}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveGoalContribution('${id}')">Registrar aporte</button></div>`)}
function saveGoalContribution(id){const v=num($('#goalAmount').value);if(!v)return showToast('Informe um valor válido');const g=data.goals.find(x=>x.id===id);g.current+=v;g.history??=[];g.history.unshift({id:uid(),date:$('#goalDate').value,amount:v,note:$('#goalNote').value.trim()||'Aporte pelo celular'});queueChange('goal_contribution',`${g.name} +${fmt(v)}`);closeModal();render()}
function openNewGoal(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova meta</div><label>Nome</label><input id="ngName" class="field" placeholder="Ex.: Notebook"/><label>Valor alvo</label><input id="ngTarget" class="field" inputmode="decimal" placeholder="R$ 0,00"/><label>Valor já guardado</label><input id="ngCurrent" class="field" inputmode="decimal" placeholder="R$ 0,00"/><label>Prazo</label><input id="ngDate" type="date" class="field" value="2027-12-31"/><label>Tipo</label><select id="ngType" class="field"><option>Compra</option><option>Viagem</option><option>Educação</option><option>Reserva</option><option>Investimento</option></select><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveNewGoal()">Salvar meta</button></div>`)}
function saveNewGoal(){const name=$('#ngName').value.trim(),target=num($('#ngTarget').value);if(!name||!target)return showToast('Informe nome e valor alvo');data.goals.unshift({id:uid(),name,target,current:num($('#ngCurrent').value),deadline:$('#ngDate').value,icon:'🎯',type:$('#ngType').value,priority:3,history:[]});queueChange('goal_created',`Meta ${name}`);closeModal();render()}
function deleteGoal(id){if(confirm('Apagar esta meta?')){data.goals=data.goals.filter(x=>x.id!==id);queueChange('goal_deleted','Meta excluída');location.hash='';nav('goals')}}
function openReserve(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Reserva de emergência</div><label>Reserva atual</label><input id="resCurrent" class="field" inputmode="decimal" value="${data.reserve.current}"/><label>Meses de segurança</label><input id="resMonths" class="field" inputmode="numeric" value="${data.reserve.months}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveReserve()">Salvar</button></div>`)}
function saveReserve(){data.reserve.current=num($('#resCurrent').value);data.reserve.months=Math.max(1,parseInt($('#resMonths').value||6));queueChange('reserve','Reserva atualizada');closeModal();render()}

function networth(){const t=totals();return `${sectionHead('Patrimônio','<button class="circle-add" onclick="openAccountForm()">+</button>')}<div class="card" style="background:linear-gradient(135deg,#edf6ff,#e6f1ff)"><div class="muted">Patrimônio líquido</div><div style="font-size:34px;font-weight:900;color:#0b408e;margin:5px 0">${fmt(t.networth)}</div><div class="small muted">Contas + investimentos − dívidas</div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Contas</div><div class="kpi-value">${fmt(t.accounts)}</div></div><div class="kpi purple"><div class="kpi-label">Investimentos</div><div class="kpi-value">${fmt(t.investments)}</div></div></div><div class="card"><div class="row-between"><div class="section-title">Minhas contas</div><button class="link-btn" onclick="openAccountForm()">+ Adicionar conta</button></div>${data.accounts.map(a=>`<div class="tx" onclick="editAccount('${a.id}')"><div class="tx-icon">${escapeHtml(a.icon||'💳')}</div><div><div class="tx-title">${escapeHtml(a.name)}</div><div class="tx-sub">${escapeHtml(a.institution||'')} • ${escapeHtml(a.type)}</div></div><div class="tx-amount">${fmt(a.balance)}</div></div>`).join('')}</div>`}
function openAccountForm(id=''){const a=id?data.accounts.find(x=>x.id===id):null;openModal(`<div class="sheet-handle"></div><div class="sheet-title">${a?'Editar conta':'Nova conta'}</div><label>Nome</label><input id="accName" class="field" value="${escapeHtml(a?.name||'')}"/><label>Instituição</label><input id="accInst" class="field" value="${escapeHtml(a?.institution||'')}"/><label>Tipo</label><input id="accType" class="field" value="${escapeHtml(a?.type||'Conta corrente')}"/><label>Saldo</label><input id="accBal" class="field" inputmode="decimal" value="${a?.balance||0}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveAccount('${id}')">Salvar</button></div>`)}
function editAccount(id){openAccountForm(id)}
function saveAccount(id){const name=$('#accName').value.trim();if(!name)return showToast('Informe o nome');if(id){const a=data.accounts.find(x=>x.id===id),oldName=a.name;a.name=name;a.institution=$('#accInst').value;a.type=$('#accType').value;a.balance=num($('#accBal').value);if(oldName!==name){data.transactions.forEach(x=>{if(x.account===oldName)x.account=name});data.recurring.forEach(x=>{if(x.account===oldName)x.account=name})}}else data.accounts.push({id:uid(),name,institution:$('#accInst').value,type:$('#accType').value,balance:num($('#accBal').value),include:true,icon:'💳'});queueChange('account','Conta atualizada');closeModal();render()}

function investments(){const total=data.investments.reduce((a,b)=>a+(b.current||0),0);return `${sectionHead('Investimentos','<button class="circle-add" onclick="openInvestmentForm()">+</button>')}<div class="card" style="background:linear-gradient(135deg,#edf6ff,#e5f1ff)"><div class="muted">Patrimônio investido</div><div style="font-size:34px;font-weight:900;color:#0b408e;margin:4px 0">${fmt(total)}</div><div class="income"><strong>Carteira consolidada</strong></div></div><div class="card"><div class="section-title">Ativos cadastrados</div>${data.investments.map(i=>{const gain=(i.current||0)-(i.invested||0);return `<div class="tx" onclick="investmentActions('${i.id}')"><div class="tx-icon">▥</div><div><div class="tx-title">${escapeHtml(i.name)}</div><div class="tx-sub">${escapeHtml(i.kind)} • ${escapeHtml(i.indexer||'')}</div></div><div><div class="tx-amount ${gain>=0?'income':'expense'}">${fmt(i.current)}</div><div class="tx-time">${gain>=0?'+ ':''}${fmt(gain)}</div></div></div>`}).join('')}</div>`}
function openInvestmentForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Novo investimento</div><label>Nome</label><input id="invName" class="field" placeholder="Ex.: Tesouro Prefixado"/><label>Classe</label><select id="invKind" class="field"><option>Renda Fixa</option><option>Renda Variável</option></select><label>Tipo</label><input id="invType" class="field" placeholder="Tesouro, CDB, Ação, FII..."/><label>Valor aplicado</label><input id="invInvested" class="field" inputmode="decimal"/><label>Valor atual</label><input id="invCurrent" class="field" inputmode="decimal"/><label>Taxa contratada (%)</label><input id="invRate" class="field" inputmode="decimal"/><label>Indexador</label><input id="invIndexer" class="field" placeholder="CDI, IPCA, Prefixado, Mercado"/><label>Instituição</label><input id="invInst" class="field"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveInvestment()">Salvar</button></div>`)}
function saveInvestment(){const name=$('#invName').value.trim();if(!name)return showToast('Informe o nome');data.investments.push({id:uid(),name,kind:$('#invKind').value,type:$('#invType').value||$('#invKind').value,invested:num($('#invInvested').value),current:num($('#invCurrent').value)||num($('#invInvested').value),rate:num($('#invRate').value),indexer:$('#invIndexer').value,institution:$('#invInst').value,color:'#2c91f5',history:[]});queueChange('investment','Investimento adicionado');closeModal();render()}
function investmentActions(id){const i=data.investments.find(x=>x.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(i.name)}</div><div class="sheet-sub">Aplicado ${fmt(i.invested)} • Atual ${fmt(i.current)}</div><label>Novo aporte</label><input id="invContribution" class="field" inputmode="decimal" placeholder="R$ 0,00"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="addInvestmentContribution('${id}')">Registrar aporte</button></div>`)}
function addInvestmentContribution(id){const v=num($('#invContribution').value);if(!v)return showToast('Informe o valor');const i=data.investments.find(x=>x.id===id);i.invested+=v;i.current+=v;i.history??=[];i.history.unshift({id:uid(),date:isoToday(),amount:v,type:'Aplicação',note:'Aporte pelo celular'});queueChange('investment_contribution',`${i.name} +${fmt(v)}`);closeModal();render()}

function budget(){const total=budgetTotal(),spent=totals().expense;return `${sectionHead('Orçamento','')}<div class="card"><div class="row-between"><div><div class="section-title">Orçamento do mês</div><div class="muted small">${fmt(spent)} gastos de ${fmt(total)} planejados</div></div><span class="chip ${spent>total?'yellow':'green'}">${Math.round(spent/(total||1)*100)}%</span></div></div>${Object.entries(data.budget).map(([cat,val])=>{const s=categorySpent(cat),p=Math.min(100,s/(val||1)*100);return `<div class="card"><div class="row-between"><div><strong>${escapeHtml(cat)}</strong><div class="muted small">${fmt(s)} de ${fmt(val)}</div></div><button class="secondary" onclick="editBudget('${encodeURIComponent(cat)}')">Editar</button></div><div class="progress ${p>=90?'yellow':'blue'}" style="margin-top:10px"><div style="width:${p}%"></div></div></div>`}).join('')}`}
function editBudget(encoded){const cat=decodeURIComponent(encoded);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(cat)}</div><label>Limite mensal</label><input id="budgetVal" class="field money-field" inputmode="decimal" value="${data.budget[cat]}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveBudget('${encodeURIComponent(cat)}')">Salvar</button></div>`)}
function saveBudget(encoded){const cat=decodeURIComponent(encoded);data.budget[cat]=num($('#budgetVal').value);queueChange('budget',`Orçamento ${cat}`);closeModal();render()}

function recurring(){return `${sectionHead('Contas fixas','<button class="circle-add" onclick="openRecurringForm()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Compromissos recorrentes</div><div class="muted small">Estimativa mensal ${fmt(monthlyRecurring())}</div></div><span class="chip blue">${data.recurring.filter(x=>x.active).length} ativos</span></div></div>${data.recurring.map(r=>`<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(r.name)}</div><div class="muted small">${escapeHtml(r.category)} • vence dia ${r.dueDay||'—'} • ${r.frequency}</div></div><strong>${fmt(r.amount)}</strong></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="toggleRecurring('${r.id}')">${r.active?'Pausar':'Ativar'}</button><button class="secondary danger" onclick="deleteRecurring('${r.id}')">Excluir</button></div></div>`).join('')}`}
function openRecurringForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova conta fixa</div><label>Nome</label><input id="recName" class="field"/><label>Valor</label><input id="recAmount" class="field" inputmode="decimal"/><label>Categoria</label><select id="recCat" class="field">${Object.keys(data.budget).map(c=>`<option>${escapeHtml(c)}</option>`).join('')}</select><label>Dia do vencimento</label><input id="recDue" class="field" inputmode="numeric"/><label>Frequência</label><select id="recFreq" class="field"><option>Mensal</option><option>Semanal</option><option>Anual</option></select><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveRecurring()">Salvar</button></div>`)}
function saveRecurring(){const name=$('#recName').value.trim();if(!name)return showToast('Informe o nome');data.recurring.push({id:uid(),name,category:$('#recCat').value,amount:num($('#recAmount').value),dueDay:parseInt($('#recDue').value||0),frequency:$('#recFreq').value,essential:true,active:true,account:''});queueChange('recurring','Conta fixa adicionada');closeModal();render()}
function toggleRecurring(id){const r=data.recurring.find(x=>x.id===id);r.active=!r.active;queueChange('recurring','Conta fixa atualizada');render()}
function deleteRecurring(id){if(confirm('Excluir esta conta fixa?')){data.recurring=data.recurring.filter(x=>x.id!==id);queueChange('recurring_deleted','Conta fixa excluída');render()}}

function debts(){const total=data.debts.reduce((a,b)=>a+b.balance,0),monthly=data.debts.reduce((a,b)=>a+b.payment,0);return `${sectionHead('Dívidas','<button class="circle-add" onclick="openDebtForm()">+</button>')}<div class="grid-2"><div class="kpi red"><div class="kpi-label">Saldo devedor</div><div class="kpi-value">${fmt(total)}</div></div><div class="kpi"><div class="kpi-label">Parcelas / mês</div><div class="kpi-value">${fmt(monthly)}</div></div></div>${data.debts.map(d=>{const rem=Math.max(0,d.totalInstallments-d.paidInstallments),p=d.original?Math.max(0,Math.min(100,(1-d.balance/d.original)*100)):0;return `<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(d.item)}</div><div class="muted small">${escapeHtml(d.creditor)} • ${d.paidInstallments}/${d.totalInstallments} parcelas</div></div><strong>${fmt(d.balance)}</strong></div><div class="progress" style="margin-top:10px"><div style="width:${p}%"></div></div><div class="goal-meta"><span>Parcela ${fmt(d.payment)}</span><span>Restam ${rem}</span></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="payDebt('${d.id}')">Registrar parcela</button><button class="secondary" onclick="amortizeDebt('${d.id}')">Amortizar</button></div></div>`}).join('')}`}
function openDebtForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova dívida</div><label>Item</label><input id="debtItem" class="field"/><label>Credor</label><input id="debtCreditor" class="field"/><label>Valor original</label><input id="debtOriginal" class="field" inputmode="decimal"/><label>Saldo atual</label><input id="debtBalance" class="field" inputmode="decimal"/><label>Parcela mensal</label><input id="debtPayment" class="field" inputmode="decimal"/><div class="sheet-row"><div><label>Nº parcelas</label><input id="debtTotal" class="field" inputmode="numeric"/></div><div><label>Pagas</label><input id="debtPaid" class="field" inputmode="numeric"/></div></div><label>Juros (%)</label><input id="debtInterest" class="field" inputmode="decimal"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveDebt()">Salvar</button></div>`)}
function saveDebt(){const item=$('#debtItem').value.trim();if(!item)return showToast('Informe o item');data.debts.push({id:uid(),item,creditor:$('#debtCreditor').value,original:num($('#debtOriginal').value),balance:num($('#debtBalance').value),payment:num($('#debtPayment').value),totalInstallments:parseInt($('#debtTotal').value||0),paidInstallments:parseInt($('#debtPaid').value||0),dueDay:10,interest:num($('#debtInterest').value),priority:3});queueChange('debt','Dívida adicionada');closeModal();render()}
function payDebt(id){const d=data.debts.find(x=>x.id===id);if(!d||Number(d.payment||0)<=0)return showToast('Parcela mensal inválida');const paid=Math.min(Number(d.payment||0),Number(d.balance||0));d.balance=Math.max(0,d.balance-paid);d.paidInstallments=Math.min(d.totalInstallments,d.paidInstallments+1);d.status=d.balance<=0.005?'QUITADA':'EM ABERTO';d.payments??=[];d.payments.unshift({id:uid(),date:isoToday(),amount:paid,type:'Parcela',note:'Registrado pelo celular'});queueChange('debt_payment',`${d.item} parcela paga`);render()}
function amortizeDebt(id){const d=data.debts.find(x=>x.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">Amortização extra</div><div class="sheet-sub">${escapeHtml(d.item)} • saldo ${fmt(d.balance)}</div><label>Valor</label><input id="debtExtra" class="field money-field" inputmode="decimal" placeholder="R$ 0,00"/><label>Observação</label><input id="debtExtraNote" class="field" placeholder="Ex.: antecipação"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveDebtAmortization('${id}')">Registrar</button></div>`)}
function saveDebtAmortization(id){const d=data.debts.find(x=>x.id===id),v=Math.min(num($('#debtExtra').value),Number(d.balance||0));if(!v)return showToast('Informe um valor válido');d.balance=Math.max(0,d.balance-v);d.status=d.balance<=0.005?'QUITADA':'EM ABERTO';d.payments??=[];d.payments.unshift({id:uid(),date:isoToday(),amount:v,type:'Amortização',note:$('#debtExtraNote').value.trim()||'Amortização pelo celular'});queueChange('debt_amortization',`${d.item} amortização ${fmt(v)}`);closeModal();render()}

function cards(){const totalInvoice=data.cards.reduce((a,b)=>a+b.invoice,0);return `${sectionHead('Cartões','<button class="circle-add" onclick="openCardForm()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Faturas atuais</div><div class="muted small">Total ${fmt(totalInvoice)}</div></div><button class="secondary" onclick="openCardPurchase()">Nova compra</button></div></div>${data.cards.map(c=>`<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(c.name)}</div><div class="muted small">${escapeHtml(c.bank)} • fecha ${c.closingDay} • vence ${c.dueDay}</div></div><strong>${fmt(c.invoice)}</strong></div><div class="goal-meta"><span>Limite ${fmt(c.limit)}</span><span>Disponível ${fmt(c.limit-c.invoice)}</span></div></div>`).join('')}<div class="card"><div class="section-title">Parcelas futuras</div>${data.installments.map(i=>`<div class="tx"><div class="tx-icon">▣</div><div><div class="tx-title">${escapeHtml(i.description)}</div><div class="tx-sub">${brDate(i.dueDate)} • ${i.installmentNo}/${i.installments}</div></div><div><div class="tx-amount">${fmt(i.amount)}</div><div class="tx-time ${i.paid?'income':''}">${i.paid?'Pago':'Aberto'}</div></div></div>`).join('')||'<div class="empty">Sem parcelas futuras.</div>'}</div>`}
function openCardForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Novo cartão</div><label>Nome</label><input id="cardName" class="field"/><label>Banco</label><input id="cardBank" class="field"/><label>Limite</label><input id="cardLimit" class="field" inputmode="decimal"/><label>Fatura atual</label><input id="cardInvoice" class="field" inputmode="decimal"/><div class="sheet-row"><div><label>Fecha dia</label><input id="cardClose" class="field" inputmode="numeric"/></div><div><label>Vence dia</label><input id="cardDue" class="field" inputmode="numeric"/></div></div><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveCard()">Salvar</button></div>`)}
function saveCard(){const name=$('#cardName').value.trim();if(!name)return showToast('Informe o nome');data.cards.push({id:uid(),name,bank:$('#cardBank').value,limit:num($('#cardLimit').value),invoice:num($('#cardInvoice').value),closingDay:parseInt($('#cardClose').value||0),dueDay:parseInt($('#cardDue').value||0)});queueChange('card','Cartão adicionado');closeModal();render()}
function openCardPurchase(){if(!data.cards.length)return showToast('Cadastre um cartão primeiro');openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova compra parcelada</div><label>Cartão</label><select id="buyCard" class="field">${data.cards.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select><label>Descrição</label><input id="buyDesc" class="field"/><label>Valor total</label><input id="buyTotal" class="field" inputmode="decimal"/><label>Número de parcelas</label><input id="buyN" class="field" inputmode="numeric" value="1"/><label>Primeiro vencimento</label><input id="buyDate" type="date" class="field" value="${isoToday()}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveCardPurchase()">Gerar parcelas</button></div>`)}
function addMonthsIso(iso,offset){const [y0,m0,d0]=String(iso||isoToday()).split('-').map(Number),base=(m0-1)+Number(offset||0),y=y0+Math.floor(base/12),m=((base%12)+12)%12+1,last=new Date(y,m,0).getDate(),d=Math.min(d0,last);return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function saveCardPurchase(){const card=data.cards.find(c=>c.id===$('#buyCard').value),total=num($('#buyTotal').value),n=Math.max(1,parseInt($('#buyN').value||1)),desc=$('#buyDesc').value.trim();if(!total||!desc)return showToast('Informe descrição e valor');data.cardPurchases??=[];const purchaseId=uid(),firstDue=$('#buyDate').value;data.cardPurchases.push({id:purchaseId,cardId:card.id,purchaseDate:isoToday(),description:desc,total,installments:n,firstDueDate:firstDue,notes:''});const cents=Math.round(total*100),base=Math.floor(cents/n),rem=cents-base*n;for(let k=0;k<n;k++){const c=(base+(k<rem?1:0))/100;data.installments.push({id:uid(),purchaseId,cardId:card.id,cardName:card.name,description:desc,installmentNo:k+1,installments:n,amount:c,dueDate:addMonthsIso(firstDue,k),paid:false,paidAt:''})}queueChange('card_purchase',`${desc} ${n}x`);closeModal();render()}

function calculator(){return `${sectionHead('Calculadoras','')}<div class="segment" id="calcSeg"><button class="active" data-calc="simple">Simples</button><button data-calc="complete">Completa</button></div><div id="calcBody">${simpleCalcForm()}</div>`}
function simpleCalcForm(){return `<div class="card form-card"><div class="section-title">Quando consigo comprar?</div><label>O que você quer comprar?</label><input id="scName" class="field" placeholder="Ex.: Monitor"/><label>Preço à vista / meta</label><input id="scTarget" class="field" inputmode="decimal"/><label>Quanto você já tem?</label><input id="scInitial" class="field" inputmode="decimal" value="0"/><label>Quanto consegue guardar?</label><input id="scContribution" class="field" inputmode="decimal"/><label>Frequência</label><select id="scFreq" class="field"><option>Semanal</option><option>Mensal</option><option>Anual</option></select><label>Rentabilidade ao ano (%)</label><input id="scRate" class="field" inputmode="decimal" value="0"/><button class="primary" onclick="runSimpleCalc()">Calcular quando consigo comprar</button></div><div id="calcResult"></div>`}
function completeCalcForm(){return `<div class="card form-card"><div class="section-title">Planejamento completo</div><label>Aporte inicial</label><input id="ccInitial" class="field" inputmode="decimal" value="0"/><label>Aporte mensal</label><input id="ccMonthly" class="field" inputmode="decimal"/><label>Rentabilidade anual (%)</label><input id="ccRate" class="field" inputmode="decimal" value="10"/><label>Prazo (anos)</label><input id="ccYears" class="field" inputmode="numeric" value="10"/><label>13º investido por ano</label><input id="cc13" class="field" inputmode="decimal" value="0"/><label>PLR investida por ano</label><input id="ccPlr" class="field" inputmode="decimal" value="0"/><label>Aporte extra anual</label><input id="ccExtra" class="field" inputmode="decimal" value="0"/><label>Inflação anual (%)</label><input id="ccInflation" class="field" inputmode="decimal" value="4.5"/><label>Meta de patrimônio</label><input id="ccTarget" class="field" inputmode="decimal" value="0"/><button class="primary" onclick="runCompleteCalc()">Calcular projeção</button></div><div id="calcResult"></div>`}
function bindCalculator(){document.querySelectorAll('#calcSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#calcSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#calcBody').innerHTML=b.dataset.calc==='simple'?simpleCalcForm():completeCalcForm()})}
function runSimpleCalc(){const target=num($('#scTarget').value),initial=num($('#scInitial').value),contrib=num($('#scContribution').value),annual=num($('#scRate').value)/100,freq=$('#scFreq').value;if(!target||!contrib)return showToast('Informe meta e aporte');const perYear=freq==='Semanal'?52:freq==='Mensal'?12:1,rate=Math.pow(1+annual,1/perYear)-1;let bal=initial,steps=0;while(bal<target&&steps<20000){bal*=1+rate;bal+=contrib;steps++}const unit=freq==='Semanal'?'semanas':freq==='Mensal'?'meses':'anos';const months=freq==='Semanal'?steps*12/52:freq==='Mensal'?steps:steps*12;$('#calcResult').innerHTML=`<div class="card"><div class="section-title">Resultado</div><div style="font-size:34px;font-weight:900;color:var(--blue)">${steps} ${unit}</div><div class="muted">aproximadamente ${months.toFixed(1).replace('.',',')} meses para atingir ${fmt(target)}</div><div class="detail-kpis" style="margin-top:12px"><div class="mini-kpi"><small>Meta</small><strong>${fmt(target)}</strong></div><div class="mini-kpi"><small>Aporte</small><strong>${fmt(contrib)}</strong></div><div class="mini-kpi"><small>Saldo final</small><strong>${fmt(bal)}</strong></div></div></div>`}
function runCompleteCalc(){let bal=num($('#ccInitial').value),monthly=num($('#ccMonthly').value),rate=num($('#ccRate').value)/100,years=Math.max(1,parseInt($('#ccYears').value||1)),extra=num($('#cc13').value)+num($('#ccPlr').value)+num($('#ccExtra').value),infl=num($('#ccInflation').value)/100,target=num($('#ccTarget').value),months=years*12,totalContrib=bal,hit=null;const rm=Math.pow(1+rate,1/12)-1;for(let m=1;m<=months;m++){bal*=1+rm;bal+=monthly;totalContrib+=monthly;if(m%12===0){bal+=extra;totalContrib+=extra}if(target&&!hit&&bal>=target)hit=m}const real=bal/Math.pow(1+infl,years);$('#calcResult').innerHTML=`<div class="card"><div class="section-title">Projeção</div><div style="font-size:32px;font-weight:900;color:var(--blue)">${fmt(bal)}</div><div class="detail-kpis" style="margin-top:12px"><div class="mini-kpi"><small>Total aportado</small><strong>${fmt(totalContrib)}</strong></div><div class="mini-kpi"><small>Rendimento</small><strong>${fmt(bal-totalContrib)}</strong></div><div class="mini-kpi"><small>Valor real</small><strong>${fmt(real)}</strong></div></div>${target?`<div class="card" style="margin-top:12px;margin-bottom:0">${hit?`Meta de ${fmt(target)} atingida em cerca de ${hit} meses.`:`Meta de ${fmt(target)} não atingida no prazo informado.`}</div>`:''}</div>`}

function health(){const h=healthSummary();return `${sectionHead('Saúde financeira','')}<div class="card"><div class="row-between"><div><div class="muted">Score financeiro</div><div style="font-size:44px;font-weight:900;color:${h.score>=75?'var(--green)':h.score>=50?'var(--yellow)':'var(--red)'}">${Math.round(h.score)}</div></div><span class="chip ${h.score>=75?'green':h.score>=50?'yellow':'blue'}">de 100</span></div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Taxa de poupança</div><div class="kpi-value">${pct(h.saveRate)}</div></div><div class="kpi red"><div class="kpi-label">Comprometimento</div><div class="kpi-value">${pct(h.debtCommit)}</div></div><div class="kpi"><div class="kpi-label">Reserva</div><div class="kpi-value">${h.reserveMonths.toFixed(1).replace('.',',')} meses</div></div><div class="kpi purple"><div class="kpi-label">Patrimônio</div><div class="kpi-value">${fmt(h.networth)}</div></div></div><div class="card"><div class="section-title">Leitura rápida</div><div class="info-list"><div class="info-row"><span>Reserva de emergência</span><strong>${h.reserveMonths>=6?'Boa':'Construindo'}</strong></div><div class="info-row"><span>Dívidas / renda</span><strong>${h.debtCommit<=20?'Controlado':'Atenção'}</strong></div><div class="info-row"><span>Taxa de poupança</span><strong>${h.saveRate>=20?'Boa':'Pode melhorar'}</strong></div></div></div>`}

function reports(){const t=totals(),cats=Object.keys(data.budget).map(c=>[c,categorySpent(c)]).sort((a,b)=>b[1]-a[1]);return `${sectionHead('Relatórios','')}<div class="grid-2"><div class="kpi green"><div class="kpi-label">Receitas</div><div class="kpi-value">${fmt(t.income)}</div></div><div class="kpi red"><div class="kpi-label">Despesas</div><div class="kpi-value">${fmt(t.expense)}</div></div></div><div class="card"><div class="section-title">Gastos por categoria</div>${cats.map(([c,v])=>{const max=Math.max(1,cats[0]?.[1]||1);return `<div style="margin:12px 0"><div class="row-between"><strong>${escapeHtml(c)}</strong><span>${fmt(v)}</span></div><div class="progress blue" style="margin-top:5px"><div style="width:${v/max*100}%"></div></div></div>`}).join('')}</div><div class="card"><div class="section-title">Resumo patrimonial</div><div class="info-list"><div class="info-row"><span>Contas</span><strong>${fmt(t.accounts)}</strong></div><div class="info-row"><span>Investimentos</span><strong>${fmt(t.investments)}</strong></div><div class="info-row"><span>Dívidas</span><strong>${fmt(t.debts)}</strong></div><div class="info-row"><span>Patrimônio líquido</span><strong>${fmt(t.networth)}</strong></div></div></div>`}

function importPage(){return `${sectionHead('Importar Nubank','')}<div class="card"><div class="section-title">Importar arquivo CSV</div><div class="muted small">Aceita CSV com Data, Descrição e Valor; se houver Identificador ele também será usado. O app detecta arquivo repetido e reaproveita as regras de classificação vindas do Windows.</div><input id="nubankFile" type="file" accept=".csv,text/csv" class="field" style="margin-top:12px"/><button class="primary" onclick="previewNubank()">Ler arquivo</button></div><div id="importPreview"></div><div class="card"><div class="section-title">Arquivos importados</div>${data.importedFiles.map(x=>`<div class="info-row"><span>${escapeHtml(x.name)}</span><strong>${x.rows} lançamentos</strong></div>`).join('')||'<div class="muted small">Nenhum arquivo importado.</div>'}</div>`}
let pendingImport=[],pendingImportName='',pendingImportHash='',pendingImportDuplicates=0;
function csvParseLine(line,sep){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(ch===sep&&!quoted){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}
async function sha256Text(txt){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(txt));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function normalizeHeader(x){return String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
function normalizeImportedDate(raw){let s=String(raw||'').trim();if(!s)return isoToday();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;if(s.includes('/')){const p=s.split('/');if(p.length===3){const [a,b,c]=p;const y=c.length===2?`20${c}`:c;return `${y}-${String(b).padStart(2,'0')}-${String(a).padStart(2,'0')}`}}return isoToday()}
function classifyImported(description,amount){const rules=data.desktopExtra?.rules||[],desc=String(description||'').toUpperCase();for(const r of rules){if(String(r.pattern||'').toUpperCase()&&desc.includes(String(r.pattern||'').toUpperCase()))return{category:r.category||'Outros',impactBudget:Number(r.impact_budget??1)!==0,ownTransfer:Number(r.is_own_transfer??0)!==0}}return amount>0?{category:'Recebimentos',impactBudget:false,ownTransfer:false}:{category:'Outros',impactBudget:true,ownTransfer:false}}
async function previewNubank(){
  const f=$('#nubankFile').files?.[0];if(!f)return showToast('Selecione um CSV');
  const txt=(await f.text()).replace(/^\uFEFF/,''),lines=txt.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return showToast('CSV vazio');
  pendingImportHash=await sha256Text(txt);pendingImportName=f.name;
  if(data.importedFiles.some(x=>x.hash&&x.hash===pendingImportHash)){pendingImport=[];$('#importPreview').innerHTML='<div class="card"><strong class="danger">Este arquivo já foi importado anteriormente.</strong></div>';return}
  const sep=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',';
  const head=csvParseLine(lines[0],sep).map(normalizeHeader),di=head.findIndex(x=>x==='data'||x==='date'||x.includes('data')),xi=head.findIndex(x=>x.includes('descr')||x==='title'||x==='description'),vi=head.findIndex(x=>x==='valor'||x==='amount'||x==='value'),ii=head.findIndex(x=>x.includes('identificador')||x==='identifier'||x==='id');
  if(di<0||xi<0||vi<0)return showToast('CSV incompatível: preciso de Data, Descrição e Valor');
  const existingIds=new Set(data.transactions.map(x=>String(x.identifier||'')).filter(Boolean));pendingImport=[];pendingImportDuplicates=0;
  for(let rowNo=1;rowNo<lines.length;rowNo++){
    const cols=csvParseLine(lines[rowNo],sep);if(!cols.some(x=>String(x).trim()))continue;
    const signed=num(cols[vi]),description=String(cols[xi]||'Lançamento Nubank').trim();if(!signed||!description)continue;
    const date=normalizeImportedDate(cols[di]),identifier=String(ii>=0?cols[ii]:'').trim()||`${date}|${signed.toFixed(2)}|${description.slice(0,100)}`;
    if(existingIds.has(identifier)||pendingImport.some(x=>x.identifier===identifier)){pendingImportDuplicates++;continue}
    const cls=classifyImported(description,signed);
    pendingImport.push({id:uid(),identifier,date,time:'',type:signed<0?'expense':'income',amount:Math.abs(signed),category:cls.category,description,account:'Nubank',impactBudget:cls.impactBudget,ownTransfer:cls.ownTransfer,icon:'NU'});
  }
  $('#importPreview').innerHTML=`<div class="card"><div class="section-title">Prévia</div><div class="muted small">${pendingImport.length} novos lançamentos • ${pendingImportDuplicates} duplicados ignorados.</div>${pendingImport.slice(0,5).map(x=>`<div class="info-row"><span>${escapeHtml(x.description)}</span><strong>${fmt(x.amount)}</strong></div>`).join('')}<button class="primary" ${pendingImport.length?'':'disabled'} onclick="confirmNubankImport()">Confirmar importação</button></div>`;
}
function confirmNubankImport(){if(!pendingImport.length)return showToast('Nenhum lançamento novo');data.transactions.unshift(...pendingImport);data.importedFiles.unshift({id:uid(),name:pendingImportName,hash:pendingImportHash,rows:pendingImport.length,date:nowIso()});queueChange('import',`Importação ${pendingImportName}`);pendingImport=[];showToast('Importação concluída');render()}

function settings(){return `${sectionHead('Configurações','')}<div class="card form-card"><label>Nome</label><input id="setName" class="field" value="${escapeHtml(data.settings.userName)}"/><label>Renda mensal</label><input id="setIncome" class="field" inputmode="decimal" value="${data.settings.monthlyIncome}"/><label>Base essencial mensal</label><input id="setEssential" class="field" inputmode="decimal" value="${data.settings.essentialBase}"/><button class="primary" onclick="saveSettings()">Salvar configurações</button></div><div class="card form-card"><div class="section-title">Google Drive</div><div class="muted small">Use um OAuth Client ID do tipo <strong>Aplicativo da Web</strong>, criado no mesmo projeto Google Cloud usado pelo programa Windows.</div><label>Google Web Client ID</label><input id="setGoogleClientId" class="field" value="${escapeHtml(state.meta.googleClientId||'')}" placeholder="000000000000-xxxx.apps.googleusercontent.com"/><button class="primary" onclick="saveGoogleClientId()">Salvar Client ID</button><label>Sincronização automática</label><select id="setAutoSync" class="field"><option value="on" ${state.meta.autoSyncEnabled!==false?'selected':''}>Ativada</option><option value="off" ${state.meta.autoSyncEnabled===false?'selected':''}>Desativada</option></select><label>Verificar alterações a cada</label><select id="setAutoSyncInterval" class="field"><option value="30" ${Number(state.meta.autoSyncIntervalSec||60)===30?'selected':''}>30 segundos</option><option value="60" ${Number(state.meta.autoSyncIntervalSec||60)===60?'selected':''}>1 minuto</option><option value="120" ${Number(state.meta.autoSyncIntervalSec||60)===120?'selected':''}>2 minutos</option><option value="300" ${Number(state.meta.autoSyncIntervalSec||60)===300?'selected':''}>5 minutos</option></select><button class="primary" onclick="saveDriveAutoSettings()">Salvar sincronização automática</button><div class="muted small" style="margin-top:10px">Alterações feitas no celular são enviadas alguns segundos depois. O app também verifica revisões novas ao voltar para a tela. Por segurança do navegador, pode ser necessário tocar em <strong>Conectar Google Drive</strong> novamente quando a sessão do Google expirar.</div></div><div class="card"><div class="section-title">Dados e segurança</div><button class="secondary" style="width:100%;margin-bottom:8px" onclick="exportSyncPackage()">Exportar backup JSON</button><button class="secondary" style="width:100%;margin-bottom:8px" onclick="triggerImport()">Importar backup JSON</button><button class="secondary danger" style="width:100%" onclick="resetDemoData()">Limpar dados locais e desconectar</button></div>`}
function saveSettings(){data.settings.userName=$('#setName').value.trim()||'Usuário';data.settings.monthlyIncome=num($('#setIncome').value);data.settings.essentialBase=num($('#setEssential').value);queueChange('settings','Configurações atualizadas');showToast('Configurações salvas');render()}
function saveGoogleClientId(){const v=$('#setGoogleClientId').value.trim();if(v&&!/^[0-9A-Za-z-]+\.apps\.googleusercontent\.com$/.test(v))return showToast('Client ID inválido');state.meta.googleClientId=v;if(!v){state.meta.syncConnected=false;clearGoogleToken();clearAutoDriveSyncTimer()}save();if(v&&state.meta.autoSyncEnabled!==false)scheduleAutoDriveSync(800);showToast(v?'Client ID salvo':'Client ID removido');render()}
function saveDriveAutoSettings(){state.meta.autoSyncEnabled=$('#setAutoSync').value==='on';state.meta.autoSyncIntervalSec=Number($('#setAutoSyncInterval').value||60);save();if(state.meta.autoSyncEnabled&&!state.meta.autoSyncConflict)scheduleAutoDriveSync(500);else clearAutoDriveSyncTimer();showToast(state.meta.autoSyncConflict?'Configuração salva; resolva o conflito antes de reativar o automático':state.meta.autoSyncEnabled?'Sincronização automática ativada':'Sincronização automática desativada');render()}

function syncCenter(){const httpsOk=location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1';const autoOn=state.meta.autoSyncEnabled!==false;const offline=!navigator.onLine;const needsLogin=autoOn&&!state.meta.syncConnected;const statusText=state.meta.autoSyncConflict?'Conflito detectado':offline?'Offline':autoOn?(needsLogin?'Auto: conectar Drive':'Auto: ativo'):'Auto: desligado';const statusClass=state.meta.autoSyncConflict||offline||needsLogin?'yellow':autoOn?'green':'yellow';return `<div class="card"><div class="row-between"><div class="section-title">Central de sincronização</div><span class="chip ${state.meta.syncConnected?'green':'yellow'}">${state.meta.syncConnected?'Drive conectado':'Configurar'}</span></div><div class="status-grid"><div class="status-box"><div class="muted small">Dispositivo</div><strong>${state.meta.deviceId}</strong></div><div class="status-box"><div class="muted small">Revisão</div><strong>${state.meta.driveLastRevision||0}</strong></div><div class="status-box"><div class="muted small">Última sincronização</div><strong>${state.meta.lastSyncAt?new Date(state.meta.lastSyncAt).toLocaleString('pt-BR'):'Ainda não'}</strong></div><div class="status-box"><div class="muted small">Alterações locais</div><strong>${state.meta.pendingChanges||0}</strong></div><div class="status-box"><div class="muted small">Automática</div><strong><span class="chip ${statusClass}">${statusText}</span></strong></div><div class="status-box"><div class="muted small">Intervalo</div><strong>${Number(state.meta.autoSyncIntervalSec||60)} s</strong></div></div>${state.meta.autoSyncLastError?`<div class="card" style="background:var(--yellowSoft);margin-top:12px;margin-bottom:0"><strong style="color:var(--yellow)">${escapeHtml(state.meta.autoSyncConflict?'Conflito de sincronização':'Sincronização automática pausada')}</strong><div class="muted small" style="margin-top:4px">${escapeHtml(state.meta.autoSyncLastError)}</div></div>`:''}${!httpsOk?'<div class="card" style="background:var(--yellowSoft);margin-top:12px;margin-bottom:0"><strong style="color:var(--yellow)">HTTPS necessário para login Google no celular</strong><div class="muted small" style="margin-top:4px">Hospede esta PWA no GitHub Pages ou outro endereço HTTPS. O acesso por IP local continua disponível apenas para testes.</div></div>':''}<div class="actions-row" style="margin-top:12px"><button class="secondary" onclick="connectGoogleDriveMobile()">Conectar Google Drive</button><button class="secondary" onclick="googleDriveSyncMobile('auto')">Sincronizar agora</button></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="googleDriveSyncMobile('download')">Baixar do Drive</button><button class="secondary" onclick="googleDriveSyncMobile('upload')">Enviar celular</button></div></div>`}
function syncPage(){return `${sectionHead('Google Drive','')}${syncCenter()}<div class="card"><div class="section-title">Fila de alterações locais</div>${state.meta.changeQueue.slice(0,12).map(q=>`<div class="tx"><div class="tx-icon">↻</div><div><div class="tx-title">${escapeHtml(q.summary)}</div><div class="tx-sub">${new Date(q.at).toLocaleString('pt-BR')}</div></div><span class="chip yellow">Pendente</span></div>`).join('')||'<div class="empty">Nenhuma alteração pendente.</div>'}</div>`}

const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
const DRIVE_FOLDER='Controle Financeiro';
const DRIVE_FILE='controle_financeiro_sync.json';
const GOOGLE_TOKEN_KEY='financeiro_google_access_token';
const GOOGLE_TOKEN_EXP_KEY='financeiro_google_access_token_exp';
let googleAccessToken=sessionStorage.getItem(GOOGLE_TOKEN_KEY)||'';
let googleAccessTokenExpiresAt=Number(sessionStorage.getItem(GOOGLE_TOKEN_EXP_KEY)||0);
let autoSyncTimer=null;
let autoSyncBusy=false;
function hasValidGoogleToken(){return !!googleAccessToken&&Date.now()<googleAccessTokenExpiresAt-30000}
function rememberGoogleToken(r){googleAccessToken=r.access_token||'';const ttl=Math.max(60,Number(r.expires_in||3600));googleAccessTokenExpiresAt=Date.now()+ttl*1000;sessionStorage.setItem(GOOGLE_TOKEN_KEY,googleAccessToken);sessionStorage.setItem(GOOGLE_TOKEN_EXP_KEY,String(googleAccessTokenExpiresAt))}
function clearGoogleToken(){googleAccessToken='';googleAccessTokenExpiresAt=0;sessionStorage.removeItem(GOOGLE_TOKEN_KEY);sessionStorage.removeItem(GOOGLE_TOKEN_EXP_KEY)}
function validateCloudPayload(payload){
  if(!payload||payload.schema!=='controle-financeiro-sync')throw new Error('Arquivo de sincronização inválido.');
  const version=Number(payload.schemaVersion||0),revision=Number(payload.revision||0);
  if(version!==1||!Number.isInteger(revision)||revision<0)throw new Error('Versão/revisão de sincronização inválida.');
  const d=payload.data;
  if(!d||typeof d!=='object')throw new Error('Base de dados da nuvem inválida.');
  for(const key of ['transactions','goals','accounts','investments','debts','recurring','cards']){
    if(!Array.isArray(d[key]))throw new Error(`Sincronização incompleta: ${key} ausente.`);
    const ids=d[key].map(x=>String(x?.id||''));
    if(ids.some(x=>!x)||new Set(ids).size!==ids.length)throw new Error(`Sincronização inválida: IDs ausentes/duplicados em ${key}.`);
  }
  for(const key of ['cardPurchases','installments']){
    if(d[key]!==undefined&&!Array.isArray(d[key]))throw new Error(`${key} inválido.`);
    if(Array.isArray(d[key])){const ids=d[key].map(x=>String(x?.id||''));if(ids.some(x=>!x)||new Set(ids).size!==ids.length)throw new Error(`IDs ausentes/duplicados em ${key}.`)}
  }
  for(const [parentKey,childKey] of [['goals','history'],['debts','payments'],['investments','history'],['investments','incomeHistory']]){
    for(const parent of d[parentKey]||[]){if(parent[childKey]===undefined)continue;if(!Array.isArray(parent[childKey]))throw new Error(`Histórico inválido em ${parentKey}.`);const ids=parent[childKey].map(x=>String(x?.id||''));if(ids.some(x=>!x)||new Set(ids).size!==ids.length)throw new Error(`IDs de histórico ausentes/duplicados em ${parentKey}.`)}
  }
  return d;
}
function stableObject(v){if(Array.isArray(v))return v.map(stableObject);if(v&&typeof v==='object'){const o={};Object.keys(v).sort().forEach(k=>o[k]=stableObject(v[k]));return o}return v}
async function hashData(v){const raw=new TextEncoder().encode(JSON.stringify(stableObject(v)));const buf=await crypto.subtle.digest('SHA-256',raw);return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cloudPayload(revision){return {schema:'controle-financeiro-sync',schemaVersion:1,revision:Number(revision||0),updatedAt:nowIso(),updatedBy:state.meta.deviceId,meta:{app:'Controle Financeiro Mobile',mobileVersion:'0.8.0'},data}}
function requireSecureGoogle(){if(!(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))throw new Error('O login Google no navegador exige HTTPS. Publique a PWA no GitHub Pages e use o endereço HTTPS como origem autorizada no Google Cloud.')}
function requestGoogleToken(interactive=true){return new Promise((resolve,reject)=>{try{requireSecureGoogle();if(hasValidGoogleToken())return resolve(googleAccessToken);if(!state.meta.googleClientId)throw new Error('Informe o Google Web Client ID em Configurações.');if(!window.google?.accounts?.oauth2)throw new Error('Biblioteca do Google ainda não carregou. Aguarde alguns segundos e tente novamente.');const client=google.accounts.oauth2.initTokenClient({client_id:state.meta.googleClientId,scope:DRIVE_SCOPE,callback:r=>{if(r.error)return reject(new Error(interactive?r.error:'AUTH_REQUIRED: não foi possível renovar a sessão Google silenciosamente. Abra o app e toque em Conectar Google Drive.'));rememberGoogleToken(r);state.meta.syncConnected=true;state.meta.autoSyncLastError='';save();resolve(googleAccessToken)}});client.requestAccessToken({prompt:interactive?(state.meta.syncConnected?'':'consent'):''})}catch(e){reject(e)}})}
async function driveFetch(url,opts={},interactiveAuth=true){if(!hasValidGoogleToken())await requestGoogleToken(interactiveAuth);const headers={...(opts.headers||{}),Authorization:`Bearer ${googleAccessToken}`};const res=await fetch(url,{...opts,headers});if(res.status===401){clearGoogleToken();await requestGoogleToken(interactiveAuth);return driveFetch(url,opts,interactiveAuth)}if(!res.ok){const t=await res.text(),err=new Error(`Google Drive ${res.status}: ${t.slice(0,240)}`);err.status=res.status;throw err}return res}
function qEscape(s){return s.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
async function driveList(q,interactiveAuth=true){
  const u='https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=100&fields=files(id,name,modifiedTime,createdTime,size,md5Checksum)&q='+encodeURIComponent(q);
  return (await (await driveFetch(u,{},interactiveAuth)).json()).files||[];
}
async function findOrCreateDriveFolder(interactiveAuth=true){
  const files=await driveList(`name='${qEscape(DRIVE_FOLDER)}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,interactiveAuth);
  if(files[0]){state.meta.driveFolderId=files[0].id;save();return files[0].id}
  const res=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:DRIVE_FOLDER,mimeType:'application/vnd.google-apps.folder',appProperties:{cf_role:'root'}})},interactiveAuth);
  const obj=await res.json();state.meta.driveFolderId=obj.id;save();return obj.id;
}
async function findDriveSyncFile(folderId,interactiveAuth=true){
  const files=await driveList(`name='${qEscape(DRIVE_FILE)}' and '${folderId}' in parents and trashed=false`,interactiveAuth);
  files.sort((a,b)=>String(b.modifiedTime||'').localeCompare(String(a.modifiedTime||'')));
  if(files.length>1)console.warn(`Foram encontrados ${files.length} arquivos de sincronização; usando o mais recente.`);
  if(files[0]){state.meta.driveFileId=files[0].id;save();return files[0]}
  state.meta.driveFileId='';save();return null;
}
async function downloadDrivePayload(interactiveAuth=true){
  const folder=await findOrCreateDriveFolder(interactiveAuth),f=await findDriveSyncFile(folder,interactiveAuth);
  if(!f)return {payload:null,file:null,folder};
  const res=await driveFetch(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`,{},interactiveAuth),payload=await res.json();
  validateCloudPayload(payload);
  return {payload,file:f,folder};
}
const SYNC_HISTORY_PREFIX='controle_financeiro_sync_backup_';
const SYNC_HISTORY_KEEP=40;
async function writeSyncSnapshot(payload,folderId,interactiveAuth=true){
  validateCloudPayload(payload);
  const stamp=new Date().toISOString().replace(/[:.]/g,'-'),rev=Number(payload.revision||0),dev=String(payload.updatedBy||'device').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,28);
  const name=`${SYNC_HISTORY_PREFIX}r${String(rev).padStart(6,'0')}_${dev}_${stamp}.json`;
  const meta={name,parents:[folderId],mimeType:'application/json',appProperties:{cf_role:'sync_snapshot',revision:String(rev)}};
  const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name,createdTime',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(meta)},interactiveAuth),obj=await r.json();
  await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${obj.id}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},interactiveAuth);
  return obj.id;
}
async function cleanupSyncSnapshots(folderId,interactiveAuth=true){
  try{
    const files=await driveList(`name contains '${qEscape(SYNC_HISTORY_PREFIX)}' and '${folderId}' in parents and trashed=false`,interactiveAuth);
    files.sort((a,b)=>String(b.createdTime||'').localeCompare(String(a.createdTime||'')));
    for(const f of files.slice(SYNC_HISTORY_KEEP))await driveFetch(`https://www.googleapis.com/drive/v3/files/${f.id}`,{method:'DELETE'},interactiveAuth);
  }catch(e){console.warn('Falha ao limpar snapshots antigos',e)}
}
async function seedHistoryIfNeeded(remote,folderId,interactiveAuth=true){
  const files=await driveList(`name contains '${qEscape(SYNC_HISTORY_PREFIX)}' and '${folderId}' in parents and trashed=false`,interactiveAuth);
  if(!files.length&&remote)await writeSyncSnapshot(remote,folderId,interactiveAuth);
}
async function uploadDrivePayload(payload,interactiveAuth=true){
  validateCloudPayload(payload);
  const folder=await findOrCreateDriveFolder(interactiveAuth);
  let f=await findDriveSyncFile(folder,interactiveAuth);
  await writeSyncSnapshot(payload,folder,interactiveAuth);
  if(!f){
    const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:DRIVE_FILE,parents:[folder],mimeType:'application/json',appProperties:{cf_role:'sync',schema:'1'}})},interactiveAuth);
    f=await r.json();state.meta.driveFileId=f.id;save();
  }
  await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${f.id}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},interactiveAuth);
  cleanupSyncSnapshots(folder,interactiveAuth);
  return f.id;
}
async function connectGoogleDriveMobile(){
  try{await requestGoogleToken(true);await findOrCreateDriveFolder(true);if(!state.meta.autoSyncConflict)state.meta.autoSyncLastError='';save();showToast(state.meta.autoSyncConflict?'Google Drive reconectado; conflito ainda precisa ser resolvido':'Google Drive conectado');if(!state.meta.autoSyncConflict)scheduleAutoDriveSync(400);render()}
  catch(e){alert(e.message)}
}
async function checkpointDrive(payload,localHash=null,remoteHash=null){
  const remoteDataHash=remoteHash||await hashData(payload.data||{}),localDataHash=localHash||await hashData(data||{});
  state.meta.driveLastRevision=Number(payload.revision||0);
  state.meta.driveLastHash=localDataHash; // compatibilidade com v0.5
  state.meta.driveLastLocalHash=localDataHash;
  state.meta.driveLastRemoteHash=remoteDataHash;
  state.meta.lastSyncAt=nowIso();state.meta.changeQueue=[];state.meta.pendingChanges=0;state.meta.syncConnected=true;state.meta.autoSyncConflict=false;state.meta.autoSyncLastError='';save();
}
async function assertRemoteUnchanged(expectedRevision,expectedHash,interactiveAuth){
  const current=(await downloadDrivePayload(interactiveAuth)).payload;
  if(!current)throw new Error('CONFLITO: o arquivo de sincronização foi removido do Google Drive durante a operação.');
  const h=await hashData(current.data||{});
  if(Number(current.revision||0)!==Number(expectedRevision)||h!==expectedHash)throw new Error('CONFLITO: a versão do Google Drive mudou enquanto a sincronização estava em andamento. Nada foi sobrescrito.');
  return current;
}
async function verifyUploadedPayload(expectedRevision,expectedHash,interactiveAuth){
  const current=(await downloadDrivePayload(interactiveAuth)).payload;
  if(!current||Number(current.revision||0)!==Number(expectedRevision)||(await hashData(current.data||{}))!==expectedHash)throw new Error('CONFLITO: outra alteração chegou ao Drive durante o envio. Seus dados locais continuam preservados.');
}
async function googleDriveSyncMobile(direction='auto',options={}){
  const silent=!!options.silent,interactiveAuth=options.interactiveAuth!==false;
  if(autoSyncBusy){if(!silent)showToast('Já existe uma sincronização em andamento');return {action:'busy'}}
  if(!['auto','upload','download'].includes(direction))return {action:'error',error:'Direção de sincronização inválida'};
  autoSyncBusy=true;
  try{
    await requestGoogleToken(interactiveAuth);
    if(!silent)showToast('Sincronizando com o Google Drive...');
    state.meta.autoSyncLastAttempt=nowIso();
    const local=cloudPayload(state.meta.driveLastRevision||0),localHash=await hashData(local.data),remoteInfo=await downloadDrivePayload(interactiveAuth),remote=remoteInfo.payload,lastRev=Number(state.meta.driveLastRevision||0);
    const lastLocalHash=state.meta.driveLastLocalHash||state.meta.driveLastHash||'',lastRemoteHash=state.meta.driveLastRemoteHash||state.meta.driveLastHash||'';
    if(!remote){
      if(direction==='download')throw new Error('Ainda não existe uma base no Google Drive.');
      local.revision=Math.max(1,lastRev+1);await uploadDrivePayload(local,interactiveAuth);const sentHash=await hashData(local.data);await verifyUploadedPayload(local.revision,sentHash,interactiveAuth);await checkpointDrive(local,sentHash,sentHash);
      if(!silent){showToast('Primeira versão enviada ao Drive');render()}return {action:'uploaded_initial',revision:local.revision};
    }
    validateCloudPayload(remote);
    const remoteRev=Number(remote.revision||0),remoteHash=await hashData(remote.data||{});
    if(remoteHash===localHash){await checkpointDrive(remote,localHash,remoteHash);if(!silent){showToast('Já está tudo sincronizado');render()}return {action:'noop',revision:remoteRev}}
    const localChanged=lastLocalHash?localHash!==lastLocalHash:(state.meta.changeQueue.length>0),remoteChanged=(lastRev||lastRemoteHash)?(remoteRev!==lastRev||remoteHash!==lastRemoteHash):true;
    if(!lastRev&&direction==='auto'){
      if(state.meta.changeQueue.length)throw new Error('CONFLITO: primeira sincronização com alterações locais. Escolha uma vez Baixar do Drive ou Enviar celular; depois o automático assume com segurança.');
      state.data=ensureData(structuredClone(remote.data||{}));data=state.data;const appliedHash=await hashData(data);await checkpointDrive(remote,appliedHash,remoteHash);
      if(!silent){showToast('Dados do Drive aplicados no celular');render()}return {action:'downloaded',revision:remoteRev};
    }
    if(direction==='download'){
      if(!silent&&!confirm('Baixar os dados do Google Drive e substituir os dados locais deste celular?'))return {action:'cancelled'};
      state.data=ensureData(structuredClone(remote.data||{}));data=state.data;const appliedHash=await hashData(data);await checkpointDrive(remote,appliedHash,remoteHash);
      if(!silent){showToast('Dados do Drive aplicados no celular');render()}return {action:'downloaded',revision:remoteRev};
    }
    if(direction==='upload'){
      if(!silent&&!confirm('Enviar os dados deste celular e substituir a versão atual do Google Drive?'))return {action:'cancelled'};
      await assertRemoteUnchanged(remoteRev,remoteHash,interactiveAuth);await seedHistoryIfNeeded(remote,remoteInfo.folder,interactiveAuth);
      local.revision=Math.max(remoteRev,lastRev)+1;await uploadDrivePayload(local,interactiveAuth);const sentHash=await hashData(local.data);await verifyUploadedPayload(local.revision,sentHash,interactiveAuth);await checkpointDrive(local,sentHash,sentHash);
      if(!silent){showToast('Dados do celular enviados ao Drive');render()}return {action:'uploaded',revision:local.revision};
    }
    if(remoteChanged&&localChanged)throw new Error('CONFLITO: o Google Drive e este celular foram alterados desde a última sincronização. Use Baixar do Drive ou Enviar celular depois de decidir qual versão deve prevalecer.');
    if(remoteChanged){state.data=ensureData(structuredClone(remote.data||{}));data=state.data;const appliedHash=await hashData(data);await checkpointDrive(remote,appliedHash,remoteHash);if(!silent){showToast('Atualização recebida do Drive');render()}return {action:'downloaded',revision:remoteRev}}
    if(localChanged){await assertRemoteUnchanged(remoteRev,remoteHash,interactiveAuth);await seedHistoryIfNeeded(remote,remoteInfo.folder,interactiveAuth);local.revision=remoteRev+1;await uploadDrivePayload(local,interactiveAuth);const sentHash=await hashData(local.data);await verifyUploadedPayload(local.revision,sentHash,interactiveAuth);await checkpointDrive(local,sentHash,sentHash);if(!silent){showToast('Alterações enviadas ao Drive');render()}return {action:'uploaded',revision:local.revision}}
    await checkpointDrive(remote,localHash,remoteHash);if(!silent){showToast('Já está tudo sincronizado');render()}return {action:'noop',revision:remoteRev};
  }catch(e){state.meta.autoSyncLastError=String(e.message||e);if(state.meta.autoSyncLastError.startsWith('CONFLITO:'))state.meta.autoSyncConflict=true;save();if(!silent)alert(e.message);return {action:'error',error:String(e.message||e)}}
  finally{autoSyncBusy=false}
}
function clearAutoDriveSyncTimer(){if(autoSyncTimer){clearTimeout(autoSyncTimer);autoSyncTimer=null}}
function autoSyncIntervalMs(){return Math.max(30,Math.min(900,Number(state.meta.autoSyncIntervalSec||60)))*1000}
function scheduleAutoDriveSync(delay=3500){clearAutoDriveSyncTimer();if(state.meta.autoSyncEnabled===false||state.meta.autoSyncConflict||!state.meta.googleClientId)return;autoSyncTimer=setTimeout(runAutoDriveSync,Math.max(250,delay))}
async function runAutoDriveSync(){
  autoSyncTimer=null;if(state.meta.autoSyncEnabled===false||state.meta.autoSyncConflict)return;
  if(document.hidden||!navigator.onLine){scheduleAutoDriveSync(autoSyncIntervalMs());return}
  const result=await googleDriveSyncMobile('auto',{silent:true,interactiveAuth:false,fromAuto:true});
  if(result?.action==='downloaded'){showToast('Dados atualizados automaticamente');render()}
  else if(result?.action==='uploaded'||result?.action==='uploaded_initial')showToast('Alterações sincronizadas automaticamente');
  else if(result?.action==='error'&&state.meta.autoSyncConflict){showToast('Conflito detectado — sincronização automática pausada');if(currentRoute==='sync')render()}
  scheduleAutoDriveSync(autoSyncIntervalMs());
}

function more(){return `${sectionHead('Mais','')}<div class="card profile"><div class="avatar">${userInitials(data.settings.userName)}</div><div><div class="goal-name">${escapeHtml(data.settings.userName)}</div><div class="muted small">Controle Financeiro Mobile v0.8.0</div></div></div><div class="card menu-card">${[
['◔','Orçamento','budget'],['↻','Contas fixas','recurring'],['▤','Dívidas e Parcelas','debts'],['▣','Cartões de crédito','cards'],['▥','Investimentos','investments'],['⌁','Calculadoras','calculator'],['♥','Saúde financeira','health'],['▥','Relatórios','reports'],['NU','Importar Nubank','import']].map(x=>`<div class="menu-row" onclick="nav('${x[2]}')"><div class="menu-icon">${x[0]}</div><div>${x[1]}</div><div class="chev">›</div></div>`).join('')}</div><div class="card menu-card"><div class="menu-row" onclick="nav('sync')"><div class="menu-icon">▲</div><div>Google Drive <div class="small ${state.meta.syncConnected?'income':'muted'}">● ${state.meta.syncConnected?'sincronizado':'não conectado'}</div></div><div class="chev">›</div></div><div class="menu-row" onclick="nav('settings')"><div class="menu-icon">⚙</div><div>Configurações e Backup</div><div class="chev">›</div></div></div>`}

function bindCalculator(){document.querySelectorAll('#calcSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#calcSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#calcBody').innerHTML=b.dataset.calc==='simple'?simpleCalcForm():completeCalcForm()})}
function exportSyncPackage(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`controle_financeiro_mobile_backup_${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();showToast('Backup exportado')}
function triggerImport(){importFile.value='';importFile.click()}
function resetDemoData(){if(confirm('Limpar todos os dados locais deste aparelho e remover a configuração local do Google Drive? A base no Google Drive não será apagada.'))store.reset()}
importFile.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const parsed=JSON.parse(await f.text());if(!parsed||!parsed.data||typeof parsed.data!=='object')throw new Error('Backup sem dados');for(const k of ['transactions','goals','accounts','investments','debts','recurring','cards'])if(!Array.isArray(parsed.data[k]))throw new Error(`Backup incompleto: ${k}`);const incoming=migrate(parsed);if(!confirm('Restaurar este backup? Os dados financeiros locais atuais serão substituídos. Por segurança, a sincronização automática ficará pausada até você escolher Enviar celular ou Baixar do Drive.'))return;state.data=ensureData(structuredClone(incoming.data));data=state.data;queueChange('backup_restore',`Backup restaurado: ${f.name}`,false);state.meta.autoSyncConflict=true;state.meta.autoSyncLastError='Backup restaurado localmente. Revise os dados e escolha Enviar celular para publicar este backup ou Baixar do Drive para descartá-lo.';save();showToast('Backup restaurado; sincronização automática pausada');render()}catch(e){console.warn(e);showToast('Arquivo de backup inválido ou incompleto')}})

function render(){const route=currentRoute;const map={home,transactions,newtx:newTransaction,goals,goaldetail:goalDetail,networth,investments,budget,recurring,debts,cards,calculator,health,reports,import:importPage,settings,sync:syncPage,more};view.innerHTML=(map[route]||more)();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route||(route==='goaldetail'&&b.dataset.route==='goals')||(route==='newtx'&&b.dataset.route==='transactions')||(route==='investments'&&b.dataset.route==='networth')));if(route==='transactions')bindTransactions();if(route==='newtx')bindTypeSeg();if(route==='goals')bindGoals();if(route==='calculator')bindCalculator();window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.route));
window.addEventListener('hashchange',()=>{const parts=location.hash.split('/');if(parts[1]){currentRoute=parts[1];render()}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=$('#installBtn');b.hidden=false;b.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;b.hidden=true;deferredPrompt=null}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('online',()=>scheduleAutoDriveSync(500));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)scheduleAutoDriveSync(700)});
window.addEventListener('focus',()=>scheduleAutoDriveSync(700));
render();
scheduleAutoDriveSync(1200);
