const $ = s => document.querySelector(s);
const view = $('#view');
const toast = $('#toast');
const modalHost = $('#modalHost');
const importFile = $('#importFile');
const fmt = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0));
const pct = n => `${Number(n||0).toFixed(1).replace('.',',')}%`;
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : Date.now()+Math.random().toString(16).slice(2));
const isoToday = () => new Date().toISOString().slice(0,10);
const nowIso = () => new Date().toISOString();
const brDate = iso => iso ? new Date(iso+'T12:00:00').toLocaleDateString('pt-BR') : '—';
const todayBR = () => new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date());
const num = raw => {
  if(typeof raw==='number') return raw;
  const s=String(raw??'').trim().replace(/\s/g,'').replace(/R\$/gi,'');
  if(!s) return 0;
  if(s.includes(',') && s.includes('.')) return Number(s.replace(/\./g,'').replace(',','.'))||0;
  if(s.includes(',')) return Number(s.replace(',','.'))||0;
  return Number(s)||0;
};
const escapeHtml = s => String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const seedData = {
  transactions:[
    {id:uid(),date:'2026-09-12',time:'14:32',type:'expense',amount:87.50,category:'Alimentação',description:'Mercado Extra',account:'Nubank',icon:'🛒'},
    {id:uid(),date:'2026-09-12',time:'08:15',type:'expense',amount:100,category:'Transporte',description:'Posto Ipiranga',account:'Nubank',icon:'⛽'},
    {id:uid(),date:'2026-09-11',time:'10:00',type:'income',amount:3150,category:'Trabalho',description:'Salário',account:'Banco Inter',icon:'💼'},
    {id:uid(),date:'2026-09-11',time:'20:45',type:'expense',amount:59.90,category:'Lazer',description:'Jogos / Lazer',account:'Carteira',icon:'🎮'},
    {id:uid(),date:'2026-09-11',time:'19:30',type:'expense',amount:45,category:'Alimentação',description:'Restaurante',account:'Carteira',icon:'🍴'},
    {id:uid(),date:'2026-09-10',time:'18:22',type:'expense',amount:32.90,category:'Saúde',description:'Farmácia',account:'Nubank',icon:'💊'}
  ],
  goals:[
    {id:uid(),name:'Monitor AOC 27"',target:700,current:120,deadline:'2026-12-30',icon:'🖥️',type:'Compra',priority:2,note:'Para melhorar meu setup e produtividade',history:[{id:uid(),date:'2026-09-12',amount:25,note:'Aporte semanal'},{id:uid(),date:'2026-09-05',amount:25,note:'Aporte semanal'},{id:uid(),date:'2026-08-29',amount:25,note:'Aporte semanal'}]},
    {id:uid(),name:'Meu Carro',target:25000,current:8500,deadline:'2027-12-31',icon:'🚗',type:'Compra',priority:3,history:[]},
    {id:uid(),name:'Entrada da Casa',target:50000,current:12000,deadline:'2028-12-31',icon:'🏠',type:'Compra',priority:1,history:[]},
    {id:uid(),name:'Viagem',target:5000,current:800,deadline:'2026-12-31',icon:'✈️',type:'Viagem',priority:4,history:[]}
  ],
  accounts:[
    {id:uid(),name:'Nubank',institution:'Nubank',type:'Conta digital',balance:2350,include:true,icon:'NU'},
    {id:uid(),name:'Carteira',institution:'Dinheiro',type:'Dinheiro em espécie',balance:780,include:true,icon:'💳'},
    {id:uid(),name:'Banco Inter',institution:'Inter',type:'Conta corrente',balance:1450,include:true,icon:'BI'},
    {id:uid(),name:'Reserva',institution:'Inter',type:'Conta poupança',balance:540,include:true,icon:'🐷'}
  ],
  investments:[
    {id:uid(),name:'Tesouro Direto',kind:'Renda Fixa',type:'Tesouro Direto',invested:3200,current:3500,rate:13.94,indexer:'Prefixado',institution:'Tesouro Nacional',maturity:'2029-01-01',color:'#2c91f5',history:[{id:uid(),date:'2026-09-12',amount:222.39,type:'Aporte'}]},
    {id:uid(),name:'CDB Banco Inter',kind:'Renda Fixa',type:'CDB / RDB',invested:2700,current:2800,rate:100,indexer:'CDI',institution:'Banco Inter',maturity:'2028-06-30',color:'#42c87d',history:[{id:uid(),date:'2026-09-05',amount:200,type:'Aporte'}]},
    {id:uid(),name:'Ações',kind:'Renda Variável',type:'Ações',invested:1100,current:1200,rate:0,indexer:'Mercado',institution:'Corretora',color:'#f6a44f',history:[]},
    {id:uid(),name:'FIIs',kind:'Renda Variável',type:'FIIs',invested:500,current:520,rate:0,indexer:'Mercado',institution:'Corretora',color:'#8f65ec',history:[]}
  ],
  debts:[
    {id:uid(),item:'Processador',creditor:'Mãe',original:825.48,balance:229.30,payment:45.86,totalInstallments:18,paidInstallments:13,dueDay:10,interest:0,priority:3},
    {id:uid(),item:'Barra fixa',creditor:'Mãe',original:115.38,balance:38.46,payment:19.23,totalInstallments:6,paidInstallments:4,dueDay:10,interest:0,priority:4}
  ],
  recurring:[
    {id:uid(),name:'Internet',category:'Contas e serviços',amount:120,dueDay:12,frequency:'Mensal',essential:true,active:true,account:'Nubank'},
    {id:uid(),name:'Faculdade',category:'Educação',amount:320,dueDay:8,frequency:'Mensal',essential:true,active:true,account:'Nubank'}
  ],
  cards:[
    {id:uid(),name:'Nubank',bank:'Nubank',limit:1800,invoice:380,closingDay:3,dueDay:10}
  ],
  cardPurchases:[],
  installments:[
    {id:uid(),cardId:null,cardName:'Nubank',description:'Teclado',installmentNo:2,installments:6,amount:85,dueDate:'2026-10-10',paid:false}
  ],
  budget:{
    'Alimentação':450,'Transporte':350,'Lazer':250,'Saúde':150,'Educação':350,'Contas e serviços':350,'Outros':200
  },
  reserve:{current:0,months:6},
  settings:{monthlyIncome:3150,essentialBase:442.49,userName:'Matheus Henrique',theme:'light',autosave:true},
  importedFiles:[],
  scenarios:[]
};

function defaultState(){return {meta:{app:'Controle Financeiro Mobile',version:'0.4.1',user:'Matheus Henrique',deviceId:`mobile-${uid().slice(0,8)}`,createdAt:nowIso(),updatedAt:nowIso(),lastSyncAt:null,syncProvider:'Google Drive',syncReady:true,syncConnected:false,pendingChanges:0,changeQueue:[],googleClientId:'',driveFolderId:'',driveFileId:'',driveLastRevision:0,driveLastHash:'',driveLastModified:''},data:JSON.parse(JSON.stringify(seedData))}}
function ensureData(d){
  const s=JSON.parse(JSON.stringify(seedData));
  d=d||{};
  for(const k of Object.keys(s)) if(d[k]===undefined) d[k]=s[k];
  if(!Array.isArray(d.debts)) d.debts=s.debts;
  if(Array.isArray(d.investments)) d.investments=d.investments.map((x,i)=>({invested:x.invested??x.value??0,current:x.current??x.value??0,kind:x.kind??'Investimento',history:x.history??[],...x}));
  return d;
}
function migrate(raw){if(!raw)return defaultState(); if(raw.meta&&raw.data){const def=defaultState();raw.data=ensureData(raw.data);raw.meta={...def.meta,...raw.meta,version:'0.4.1'};return raw} const st=defaultState();st.data=ensureData(raw);return st}
const store={get(){try{return migrate(JSON.parse(localStorage.getItem('financeiro_mobile_state')))}catch{return defaultState()}},set(v){localStorage.setItem('financeiro_mobile_state',JSON.stringify(v))},reset(){localStorage.removeItem('financeiro_mobile_state');location.reload()}};
let state=store.get(),data=state.data,currentRoute='home',deferredPrompt=null;
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast._t);showToast._t=setTimeout(()=>toast.classList.remove('show'),2200)}
function save(){state.data=data;state.meta.updatedAt=nowIso();state.meta.pendingChanges=state.meta.changeQueue.length;store.set(state)}
function queueChange(type,summary){state.meta.changeQueue.unshift({id:uid(),type,summary,at:nowIso(),deviceId:state.meta.deviceId});state.meta.changeQueue=state.meta.changeQueue.slice(0,100);save()}
function nav(route){currentRoute=route;if(location.hash)history.replaceState(null,'',location.pathname);render()}
function openModal(content){modalHost.innerHTML=`<div class="sheet">${content}</div>`;modalHost.classList.remove('hidden')}
function closeModal(){modalHost.classList.add('hidden');modalHost.innerHTML=''}
modalHost.addEventListener('click',e=>{if(e.target===modalHost)closeModal()});
function latestPeriod(){
  const dates=(data.transactions||[]).map(x=>x.date).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x||'')).sort();
  const d=dates.length?dates[dates.length-1]:isoToday();
  return {year:Number(d.slice(0,4)),month:Number(d.slice(5,7))};
}
function inPeriod(tx,year,month){
  if(!tx?.date)return false;
  return Number(tx.date.slice(0,4))===Number(year)&&Number(tx.date.slice(5,7))===Number(month);
}
function flowTotals(year,month){
  let income=0,expense=0,investmentContrib=0,withdrawals=0;
  for(const x of (data.transactions||[])){
    if(!inPeriod(x,year,month))continue;
    if(x.ownTransfer===true||x.ownTransfer===1)continue;
    const amount=Math.abs(Number(x.amount||0));
    if(x.type==='expense'&&x.category==='Investimentos'){investmentContrib+=amount;continue;}
    if(x.type==='income'&&x.category==='Resgate de investimento'){withdrawals+=amount;continue;}
    if(x.type==='income')income+=amount;
    else if(x.type==='expense'&&x.impactBudget!==false&&x.impactBudget!==0)expense+=amount;
  }
  return {income,expense,balance:income-expense,investmentContrib,withdrawals};
}
function totals(){
  const period=latestPeriod(),flow=flowTotals(period.year,period.month);
  const accounts=data.accounts.filter(x=>x.include!==false).reduce((a,b)=>a+Number(b.balance||0),0);
  const investments=data.investments.reduce((a,b)=>a+Number(b.current||0),0);
  const debts=data.debts.reduce((a,b)=>a+Number(b.balance||0),0);
  return {...flow,accounts,investments,debts,networth:accounts+investments-debts,period};
}
function budgetTotal(){return Object.values(data.budget).reduce((a,b)=>a+Number(b||0),0)}
function monthlyRecurring(){return data.recurring.filter(x=>x.active).reduce((a,b)=>a+(x.frequency==='Mensal'?x.amount:x.frequency==='Semanal'?x.amount*4.33:x.amount/12),0)}
function reserveSummary(){const base=data.settings.essentialBase||monthlyRecurring()||0,target=base*(data.reserve.months||6),current=data.reserve.current||0;return{base,target,current,missing:Math.max(0,target-current),progress:target?current/target*100:0}}
function healthSummary(){const t=totals(),r=reserveSummary(),income=data.settings.monthlyIncome||t.income||1,debtMonthly=data.debts.reduce((a,b)=>a+(b.payment||0),0),saveRate=Math.max(0,(income-t.expense)/income*100),debtCommit=debtMonthly/income*100,reserveMonths=r.base?r.current/r.base:0;let score=50+Math.min(20,saveRate*.7)+Math.min(20,reserveMonths*4)-Math.min(25,debtCommit*.8);score=Math.max(0,Math.min(100,score));return{score,saveRate,debtCommit,reserveMonths,networth:t.networth}}
function categorySpent(cat){const p=latestPeriod();return data.transactions.filter(x=>inPeriod(x,p.year,p.month)&&x.type==='expense'&&x.category===cat&&x.category!=='Investimentos'&&x.ownTransfer!==true&&x.ownTransfer!==1&&x.impactBudget!==false&&x.impactBudget!==0).reduce((a,b)=>a+Number(b.amount||0),0)}
function progressPct(g){return Math.min(100,Math.round((g.current/g.target)*100||0))}
function sectionHead(title,action=''){return `<div class="page-head"><div class="page-title">${title}</div>${action}</div>`}

function home(){const t=totals(),bt=budgetTotal(),bp=Math.min(100,Math.round(t.expense/(bt||1)*100));return `<section><div class="hero-greeting">Olá, ${escapeHtml(data.settings.userName.split(' ')[0]||'Matheus')} 👋</div><div class="date-line">${todayBR()}</div><div class="card sync-card" onclick="nav('sync')"><div class="drive-icon">▲</div><div style="flex:1"><div class="row-between"><div><div class="sync-title">Google Drive preparado</div><div class="sync-sub"><span class="dot"></span>PC e celular poderão usar a mesma base</div></div><span class="chip blue">${state.meta.pendingChanges} pend.</span></div></div></div><div class="card balance-card"><div class="balance-label">Saldo das movimentações</div><div class="balance-value">${fmt(t.balance)}</div><div class="balance-note"><strong>●</strong> dados salvos neste aparelho</div><div class="mini-stats"><div class="mini-pill">Patrimônio ${fmt(t.networth)}</div><div class="mini-pill">Dívidas ${fmt(t.debts)}</div></div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Receitas</div><div class="kpi-value">${fmt(t.income)}</div></div><div class="kpi red"><div class="kpi-label">Gastos</div><div class="kpi-value">${fmt(t.expense)}</div></div></div><div class="card"><div class="section-title">Ações rápidas</div><div class="quick-actions"><button class="quick" onclick="openNewTransaction()"><div class="qicon">⇄</div><small>Movimentar</small></button><button class="quick" onclick="nav('goals')"><div class="qicon">◎</div><small>Metas</small></button><button class="quick" onclick="nav('cards')"><div class="qicon">▣</div><small>Cartões</small></button><button class="quick" onclick="nav('investments')"><div class="qicon">▥</div><small>Investimentos</small></button></div></div><div class="card"><div class="row-between"><div><div class="section-title">Resumo do mês</div><div class="muted small">Transferências próprias e aportes não entram em Receitas/Gastos</div></div><div class="muted small">Orçamento ${fmt(bt)}</div></div><div class="progress ${bp>=90?'yellow':'blue'}"><div style="width:${bp}%"></div></div><div style="margin-top:9px"><strong>${bp}%</strong> <span class="muted">do orçamento utilizado</span></div><div class="small muted">${fmt(t.expense)} de ${fmt(bt)}</div></div><div class="card"><div class="row-between"><div class="section-title">Saúde financeira</div><button class="link-btn" onclick="nav('health')">Ver detalhes</button></div>${healthCard()}</div></section>`}
function healthCard(){const h=healthSummary();return `<div class="row-between"><div><div style="font-size:34px;font-weight:900;color:${h.score>=75?'var(--green)':h.score>=50?'var(--yellow)':'var(--red)'}">${Math.round(h.score)}/100</div><div class="muted small">Pontuação estimada</div></div><span class="chip ${h.score>=75?'green':h.score>=50?'yellow':'blue'}">Reserva ${h.reserveMonths.toFixed(1).replace('.',',')} meses</span></div>`}

function groupedTransactions(list){const groups={};list.forEach(x=>(groups[x.date]??=[]).push(x));return Object.keys(groups).sort().reverse().map(date=>`<div class="tx-group-title">${date===isoToday()?'Hoje':brDate(date)}</div><div class="card">${groups[date].map(tx=>`<div class="tx" onclick="openTxActions('${tx.id}')"><div class="tx-icon">${tx.icon||'•'}</div><div><div class="tx-title">${escapeHtml(tx.description)}</div><div class="tx-sub">${escapeHtml(tx.category)} • ${escapeHtml(tx.account||'Conta')}</div></div><div><div class="tx-amount ${tx.type==='income'?'income':'expense'}">${tx.type==='income'?'+ ':'- '}${fmt(tx.amount)}</div><div class="tx-time">${tx.time||''}</div></div></div>`).join('')}</div>`).join('')}
function transactions(){return `${sectionHead('Movimentações','<button class="secondary" onclick="nav(\'import\')">Importar</button>')}<div class="segment" id="txSeg"><button class="active" data-filter="all">Todas</button><button data-filter="income">Receitas</button><button data-filter="expense">Despesas</button></div><input id="txSearch" class="search" placeholder="Buscar movimentações..."/><div id="txList">${groupedTransactions(data.transactions)}</div><button class="fab" onclick="openNewTransaction()">+</button>`}
function bindTransactions(){const buttons=[...document.querySelectorAll('#txSeg button')],search=$('#txSearch');function apply(){const f=document.querySelector('#txSeg button.active').dataset.filter,q=(search.value||'').toLowerCase(),list=data.transactions.filter(x=>(f==='all'||x.type===f)&&`${x.description} ${x.category} ${x.account||''}`.toLowerCase().includes(q));$('#txList').innerHTML=list.length?groupedTransactions(list):'<div class="empty">Nenhuma movimentação encontrada.</div>'}buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');apply()});search.oninput=apply}
function openNewTransaction(){currentRoute='newtx';render()}
function newTransaction(){return `${sectionHead('Nova Movimentação','')}<div class="card form-card"><div class="segment" id="typeSeg"><button class="active" data-type="expense">Despesa</button><button data-type="income">Receita</button></div><label>Valor</label><input id="txAmount" class="field money-field" inputmode="decimal" placeholder="R$ 0,00"/><label>Categoria</label><select id="txCategory" class="field">${Object.keys(data.budget).map(c=>`<option>${c}</option>`).join('')}<option>Trabalho</option><option>Investimentos</option></select><label>Descrição</label><input id="txDescription" class="field" placeholder="Ex.: Mercado, combustível, salário..."/><label>Data</label><input id="txDate" type="date" class="field" value="${isoToday()}"/><label>Conta</label><select id="txAccount" class="field">${data.accounts.map(a=>`<option>${escapeHtml(a.name)}</option>`).join('')}</select><button class="primary" onclick="saveTransaction()">Salvar movimentação</button></div>`}
function bindTypeSeg(){document.querySelectorAll('#typeSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#typeSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function saveTransaction(){const amount=num($('#txAmount').value),desc=$('#txDescription').value.trim();if(!amount||!desc)return showToast('Informe valor e descrição');const type=document.querySelector('#typeSeg button.active').dataset.type;data.transactions.unshift({id:uid(),date:$('#txDate').value,time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),type,amount,category:$('#txCategory').value,description:desc,account:$('#txAccount').value,icon:type==='income'?'💼':'🧾'});queueChange('transaction',`${type==='income'?'Receita':'Despesa'} ${fmt(amount)}`);showToast('Movimentação salva');nav('transactions')}
function openTxActions(id){const x=data.transactions.find(t=>t.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(x.description)}</div><div class="sheet-sub">${brDate(x.date)} • ${escapeHtml(x.category)} • ${fmt(x.amount)}</div><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Fechar</button><button class="primary danger-btn" onclick="deleteTransaction('${id}')">Excluir</button></div>`)}
function deleteTransaction(id){data.transactions=data.transactions.filter(x=>x.id!==id);queueChange('transaction_deleted','Movimentação excluída');closeModal();render()}

function goals(){const r=reserveSummary();return `${sectionHead('Metas & reserva','<button class="circle-add" onclick="openNewGoal()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Reserva de emergência</div><div class="muted small">${fmt(r.current)} de ${fmt(r.target)} • ${data.reserve.months} meses</div></div><button class="secondary" onclick="openReserve()">Atualizar</button></div><div class="progress" style="margin-top:10px"><div style="width:${Math.min(100,r.progress)}%"></div></div><div class="small muted" style="margin-top:6px">Faltam ${fmt(r.missing)}</div></div><div class="segment" id="goalSeg"><button class="active" data-goal-filter="all">Todas</button><button data-goal-filter="open">Em andamento</button><button data-goal-filter="done">Concluídas</button></div><div id="goalList">${goalCards(data.goals)}</div>`}
function goalCards(list){return list.length?list.map(g=>{const p=progressPct(g);return `<div class="card goal-card" onclick="openGoal('${g.id}')"><div class="goal-top"><div class="goal-icon">${g.icon||'🎯'}</div><div><div class="goal-name">${escapeHtml(g.name)}</div><div class="goal-money"><strong>${fmt(g.current)}</strong> de ${fmt(g.target)}</div></div><span class="chip ${p>=100?'green':'blue'}">${p}%</span></div><div class="goal-bottom"><div class="progress"><div style="width:${p}%"></div></div><div class="pct">${p}%</div></div><div class="goal-meta"><span>Faltam <strong>${fmt(Math.max(0,g.target-g.current))}</strong></span><span>${brDate(g.deadline)}</span></div></div>`}).join(''):'<div class="empty">Nenhuma meta.</div>'}
function bindGoals(){document.querySelectorAll('#goalSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#goalSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.goalFilter,l=data.goals.filter(g=>f==='all'||(f==='done'?g.current>=g.target:g.current<g.target));$('#goalList').innerHTML=goalCards(l)})}
function openGoal(id){currentRoute='goaldetail';location.hash=`#/goaldetail/${id}`;render()}
function goalDetail(){const id=location.hash.split('/')[2],g=data.goals.find(x=>x.id===id)||data.goals[0],p=progressPct(g);return `${sectionHead('Detalhe da Meta','<button class="secondary danger" onclick="deleteGoal(\''+g.id+'\')">Apagar</button>')}<div class="card"><div class="goal-top"><div class="goal-icon">${g.icon||'🎯'}</div><div><div class="goal-name">${escapeHtml(g.name)}</div><div class="tx-sub">${escapeHtml(g.note||g.type||'Objetivo financeiro')}</div></div><span class="chip ${p>=100?'green':'blue'}">${p>=100?'Concluída':'Em andamento'}</span></div><div class="detail-kpis" style="margin-top:15px"><div class="mini-kpi"><small>Valor da meta</small><strong>${fmt(g.target)}</strong></div><div class="mini-kpi"><small>Guardado</small><strong>${fmt(g.current)}</strong></div><div class="mini-kpi"><small>Falta</small><strong>${fmt(Math.max(0,g.target-g.current))}</strong></div></div><div class="progress" style="margin-top:16px"><div style="width:${p}%"></div></div></div><div class="card"><div class="row-between"><div class="section-title">Histórico de aportes</div><button class="secondary" onclick="openGoalContribution('${g.id}')">+ Adicionar</button></div>${(g.history||[]).map(h=>`<div class="tx"><div class="tx-icon" style="background:var(--greenSoft);color:var(--green)">↗</div><div><div class="tx-title">${escapeHtml(h.note||'Aporte')}</div><div class="tx-sub">${brDate(h.date)}</div></div><div class="tx-amount income">+ ${fmt(h.amount)}</div></div>`).join('')||'<div class="empty">Nenhum aporte registrado.</div>'}</div>`}
function openGoalContribution(id){const g=data.goals.find(x=>x.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">Adicionar valor</div><div class="sheet-sub">${escapeHtml(g.name)} • Guardado ${fmt(g.current)} de ${fmt(g.target)}</div><label>Valor do aporte</label><input id="goalAmount" class="field money-field" inputmode="decimal" placeholder="R$ 0,00"/><label>Observação</label><input id="goalNote" class="field" placeholder="Ex.: aporte semanal"/><label>Data</label><input id="goalDate" type="date" class="field" value="${isoToday()}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveGoalContribution('${id}')">Registrar aporte</button></div>`)}
function saveGoalContribution(id){const v=num($('#goalAmount').value);if(!v)return showToast('Informe um valor válido');const g=data.goals.find(x=>x.id===id);g.current+=v;g.history??=[];g.history.unshift({id:uid(),date:$('#goalDate').value,amount:v,note:$('#goalNote').value.trim()||'Aporte pelo celular'});queueChange('goal_contribution',`${g.name} +${fmt(v)}`);closeModal();render()}
function openNewGoal(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova meta</div><label>Nome</label><input id="ngName" class="field" placeholder="Ex.: Notebook"/><label>Valor alvo</label><input id="ngTarget" class="field" inputmode="decimal" placeholder="R$ 0,00"/><label>Valor já guardado</label><input id="ngCurrent" class="field" inputmode="decimal" placeholder="R$ 0,00"/><label>Prazo</label><input id="ngDate" type="date" class="field" value="2027-12-31"/><label>Tipo</label><select id="ngType" class="field"><option>Compra</option><option>Viagem</option><option>Educação</option><option>Reserva</option><option>Investimento</option></select><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveNewGoal()">Salvar meta</button></div>`)}
function saveNewGoal(){const name=$('#ngName').value.trim(),target=num($('#ngTarget').value);if(!name||!target)return showToast('Informe nome e valor alvo');data.goals.unshift({id:uid(),name,target,current:num($('#ngCurrent').value),deadline:$('#ngDate').value,icon:'🎯',type:$('#ngType').value,priority:3,history:[]});queueChange('goal_created',`Meta ${name}`);closeModal();render()}
function deleteGoal(id){if(confirm('Apagar esta meta?')){data.goals=data.goals.filter(x=>x.id!==id);queueChange('goal_deleted','Meta excluída');location.hash='';nav('goals')}}
function openReserve(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Reserva de emergência</div><label>Reserva atual</label><input id="resCurrent" class="field" inputmode="decimal" value="${data.reserve.current}"/><label>Meses de segurança</label><input id="resMonths" class="field" inputmode="numeric" value="${data.reserve.months}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveReserve()">Salvar</button></div>`)}
function saveReserve(){data.reserve.current=num($('#resCurrent').value);data.reserve.months=Math.max(1,parseInt($('#resMonths').value||6));queueChange('reserve','Reserva atualizada');closeModal();render()}

function networth(){const t=totals();return `${sectionHead('Patrimônio','<button class="circle-add" onclick="openAccountForm()">+</button>')}<div class="card" style="background:linear-gradient(135deg,#edf6ff,#e6f1ff)"><div class="muted">Patrimônio líquido</div><div style="font-size:34px;font-weight:900;color:#0b408e;margin:5px 0">${fmt(t.networth)}</div><div class="small muted">Contas + investimentos − dívidas</div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Contas</div><div class="kpi-value">${fmt(t.accounts)}</div></div><div class="kpi purple"><div class="kpi-label">Investimentos</div><div class="kpi-value">${fmt(t.investments)}</div></div></div><div class="card"><div class="row-between"><div class="section-title">Minhas contas</div><button class="link-btn" onclick="openAccountForm()">+ Adicionar conta</button></div>${data.accounts.map(a=>`<div class="tx" onclick="editAccount('${a.id}')"><div class="tx-icon">${escapeHtml(a.icon||'💳')}</div><div><div class="tx-title">${escapeHtml(a.name)}</div><div class="tx-sub">${escapeHtml(a.institution||'')} • ${escapeHtml(a.type)}</div></div><div class="tx-amount">${fmt(a.balance)}</div></div>`).join('')}</div>`}
function openAccountForm(id=''){const a=id?data.accounts.find(x=>x.id===id):null;openModal(`<div class="sheet-handle"></div><div class="sheet-title">${a?'Editar conta':'Nova conta'}</div><label>Nome</label><input id="accName" class="field" value="${escapeHtml(a?.name||'')}"/><label>Instituição</label><input id="accInst" class="field" value="${escapeHtml(a?.institution||'')}"/><label>Tipo</label><input id="accType" class="field" value="${escapeHtml(a?.type||'Conta corrente')}"/><label>Saldo</label><input id="accBal" class="field" inputmode="decimal" value="${a?.balance||0}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveAccount('${id}')">Salvar</button></div>`)}
function editAccount(id){openAccountForm(id)}
function saveAccount(id){const name=$('#accName').value.trim();if(!name)return showToast('Informe o nome');if(id){const a=data.accounts.find(x=>x.id===id);a.name=name;a.institution=$('#accInst').value;a.type=$('#accType').value;a.balance=num($('#accBal').value)}else data.accounts.push({id:uid(),name,institution:$('#accInst').value,type:$('#accType').value,balance:num($('#accBal').value),include:true,icon:'💳'});queueChange('account','Conta atualizada');closeModal();render()}

function investments(){const total=data.investments.reduce((a,b)=>a+(b.current||0),0);return `${sectionHead('Investimentos','<button class="circle-add" onclick="openInvestmentForm()">+</button>')}<div class="card" style="background:linear-gradient(135deg,#edf6ff,#e5f1ff)"><div class="muted">Patrimônio investido</div><div style="font-size:34px;font-weight:900;color:#0b408e;margin:4px 0">${fmt(total)}</div><div class="income"><strong>Carteira consolidada</strong></div></div><div class="card"><div class="section-title">Ativos cadastrados</div>${data.investments.map(i=>{const gain=(i.current||0)-(i.invested||0);return `<div class="tx" onclick="investmentActions('${i.id}')"><div class="tx-icon">▥</div><div><div class="tx-title">${escapeHtml(i.name)}</div><div class="tx-sub">${escapeHtml(i.kind)} • ${escapeHtml(i.indexer||'')}</div></div><div><div class="tx-amount ${gain>=0?'income':'expense'}">${fmt(i.current)}</div><div class="tx-time">${gain>=0?'+ ':''}${fmt(gain)}</div></div></div>`}).join('')}</div>`}
function openInvestmentForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Novo investimento</div><label>Nome</label><input id="invName" class="field" placeholder="Ex.: Tesouro Prefixado"/><label>Classe</label><select id="invKind" class="field"><option>Renda Fixa</option><option>Renda Variável</option></select><label>Tipo</label><input id="invType" class="field" placeholder="Tesouro, CDB, Ação, FII..."/><label>Valor aplicado</label><input id="invInvested" class="field" inputmode="decimal"/><label>Valor atual</label><input id="invCurrent" class="field" inputmode="decimal"/><label>Taxa contratada (%)</label><input id="invRate" class="field" inputmode="decimal"/><label>Indexador</label><input id="invIndexer" class="field" placeholder="CDI, IPCA, Prefixado, Mercado"/><label>Instituição</label><input id="invInst" class="field"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveInvestment()">Salvar</button></div>`)}
function saveInvestment(){const name=$('#invName').value.trim();if(!name)return showToast('Informe o nome');data.investments.push({id:uid(),name,kind:$('#invKind').value,type:$('#invType').value||$('#invKind').value,invested:num($('#invInvested').value),current:num($('#invCurrent').value)||num($('#invInvested').value),rate:num($('#invRate').value),indexer:$('#invIndexer').value,institution:$('#invInst').value,color:'#2c91f5',history:[]});queueChange('investment','Investimento adicionado');closeModal();render()}
function investmentActions(id){const i=data.investments.find(x=>x.id===id);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(i.name)}</div><div class="sheet-sub">Aplicado ${fmt(i.invested)} • Atual ${fmt(i.current)}</div><label>Novo aporte</label><input id="invContribution" class="field" inputmode="decimal" placeholder="R$ 0,00"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="addInvestmentContribution('${id}')">Registrar aporte</button></div>`)}
function addInvestmentContribution(id){const v=num($('#invContribution').value);if(!v)return showToast('Informe o valor');const i=data.investments.find(x=>x.id===id);i.invested+=v;i.current+=v;i.history??=[];i.history.unshift({id:uid(),date:isoToday(),amount:v,type:'Aporte'});queueChange('investment_contribution',`${i.name} +${fmt(v)}`);closeModal();render()}

function budget(){const total=budgetTotal(),spent=totals().expense;return `${sectionHead('Orçamento','')}<div class="card"><div class="row-between"><div><div class="section-title">Orçamento do mês</div><div class="muted small">${fmt(spent)} gastos de ${fmt(total)} planejados</div></div><span class="chip ${spent>total?'yellow':'green'}">${Math.round(spent/(total||1)*100)}%</span></div></div>${Object.entries(data.budget).map(([cat,val])=>{const s=categorySpent(cat),p=Math.min(100,s/(val||1)*100);return `<div class="card"><div class="row-between"><div><strong>${escapeHtml(cat)}</strong><div class="muted small">${fmt(s)} de ${fmt(val)}</div></div><button class="secondary" onclick="editBudget('${encodeURIComponent(cat)}')">Editar</button></div><div class="progress ${p>=90?'yellow':'blue'}" style="margin-top:10px"><div style="width:${p}%"></div></div></div>`}).join('')}`}
function editBudget(encoded){const cat=decodeURIComponent(encoded);openModal(`<div class="sheet-handle"></div><div class="sheet-title">${escapeHtml(cat)}</div><label>Limite mensal</label><input id="budgetVal" class="field money-field" inputmode="decimal" value="${data.budget[cat]}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveBudget('${encodeURIComponent(cat)}')">Salvar</button></div>`)}
function saveBudget(encoded){const cat=decodeURIComponent(encoded);data.budget[cat]=num($('#budgetVal').value);queueChange('budget',`Orçamento ${cat}`);closeModal();render()}

function recurring(){return `${sectionHead('Contas fixas','<button class="circle-add" onclick="openRecurringForm()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Compromissos recorrentes</div><div class="muted small">Estimativa mensal ${fmt(monthlyRecurring())}</div></div><span class="chip blue">${data.recurring.filter(x=>x.active).length} ativos</span></div></div>${data.recurring.map(r=>`<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(r.name)}</div><div class="muted small">${escapeHtml(r.category)} • vence dia ${r.dueDay||'—'} • ${r.frequency}</div></div><strong>${fmt(r.amount)}</strong></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="toggleRecurring('${r.id}')">${r.active?'Pausar':'Ativar'}</button><button class="secondary danger" onclick="deleteRecurring('${r.id}')">Excluir</button></div></div>`).join('')}`}
function openRecurringForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova conta fixa</div><label>Nome</label><input id="recName" class="field"/><label>Valor</label><input id="recAmount" class="field" inputmode="decimal"/><label>Categoria</label><select id="recCat" class="field">${Object.keys(data.budget).map(c=>`<option>${c}</option>`).join('')}</select><label>Dia do vencimento</label><input id="recDue" class="field" inputmode="numeric"/><label>Frequência</label><select id="recFreq" class="field"><option>Mensal</option><option>Semanal</option><option>Anual</option></select><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveRecurring()">Salvar</button></div>`)}
function saveRecurring(){const name=$('#recName').value.trim();if(!name)return showToast('Informe o nome');data.recurring.push({id:uid(),name,category:$('#recCat').value,amount:num($('#recAmount').value),dueDay:parseInt($('#recDue').value||0),frequency:$('#recFreq').value,essential:true,active:true,account:''});queueChange('recurring','Conta fixa adicionada');closeModal();render()}
function toggleRecurring(id){const r=data.recurring.find(x=>x.id===id);r.active=!r.active;queueChange('recurring','Conta fixa atualizada');render()}
function deleteRecurring(id){if(confirm('Excluir esta conta fixa?')){data.recurring=data.recurring.filter(x=>x.id!==id);queueChange('recurring_deleted','Conta fixa excluída');render()}}

function debts(){const total=data.debts.reduce((a,b)=>a+b.balance,0),monthly=data.debts.reduce((a,b)=>a+b.payment,0);return `${sectionHead('Dívidas','<button class="circle-add" onclick="openDebtForm()">+</button>')}<div class="grid-2"><div class="kpi red"><div class="kpi-label">Saldo devedor</div><div class="kpi-value">${fmt(total)}</div></div><div class="kpi"><div class="kpi-label">Parcelas / mês</div><div class="kpi-value">${fmt(monthly)}</div></div></div>${data.debts.map(d=>{const rem=Math.max(0,d.totalInstallments-d.paidInstallments),p=d.original?Math.max(0,Math.min(100,(1-d.balance/d.original)*100)):0;return `<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(d.item)}</div><div class="muted small">${escapeHtml(d.creditor)} • ${d.paidInstallments}/${d.totalInstallments} parcelas</div></div><strong>${fmt(d.balance)}</strong></div><div class="progress" style="margin-top:10px"><div style="width:${p}%"></div></div><div class="goal-meta"><span>Parcela ${fmt(d.payment)}</span><span>Restam ${rem}</span></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="payDebt('${d.id}')">Registrar parcela</button><button class="secondary" onclick="amortizeDebt('${d.id}')">Amortizar</button></div></div>`}).join('')}`}
function openDebtForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova dívida</div><label>Item</label><input id="debtItem" class="field"/><label>Credor</label><input id="debtCreditor" class="field"/><label>Valor original</label><input id="debtOriginal" class="field" inputmode="decimal"/><label>Saldo atual</label><input id="debtBalance" class="field" inputmode="decimal"/><label>Parcela mensal</label><input id="debtPayment" class="field" inputmode="decimal"/><div class="sheet-row"><div><label>Nº parcelas</label><input id="debtTotal" class="field" inputmode="numeric"/></div><div><label>Pagas</label><input id="debtPaid" class="field" inputmode="numeric"/></div></div><label>Juros (%)</label><input id="debtInterest" class="field" inputmode="decimal"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveDebt()">Salvar</button></div>`)}
function saveDebt(){const item=$('#debtItem').value.trim();if(!item)return showToast('Informe o item');data.debts.push({id:uid(),item,creditor:$('#debtCreditor').value,original:num($('#debtOriginal').value),balance:num($('#debtBalance').value),payment:num($('#debtPayment').value),totalInstallments:parseInt($('#debtTotal').value||0),paidInstallments:parseInt($('#debtPaid').value||0),dueDay:10,interest:num($('#debtInterest').value),priority:3});queueChange('debt','Dívida adicionada');closeModal();render()}
function payDebt(id){const d=data.debts.find(x=>x.id===id);d.balance=Math.max(0,d.balance-d.payment);d.paidInstallments=Math.min(d.totalInstallments,d.paidInstallments+1);queueChange('debt_payment',`${d.item} parcela paga`);render()}
function amortizeDebt(id){const raw=prompt('Valor da amortização extra:');const v=num(raw);if(!v)return;const d=data.debts.find(x=>x.id===id);d.balance=Math.max(0,d.balance-v);queueChange('debt_amortization',`${d.item} amortização ${fmt(v)}`);render()}

function cards(){const totalInvoice=data.cards.reduce((a,b)=>a+b.invoice,0);return `${sectionHead('Cartões','<button class="circle-add" onclick="openCardForm()">+</button>')}<div class="card"><div class="row-between"><div><div class="section-title">Faturas atuais</div><div class="muted small">Total ${fmt(totalInvoice)}</div></div><button class="secondary" onclick="openCardPurchase()">Nova compra</button></div></div>${data.cards.map(c=>`<div class="card"><div class="row-between"><div><div class="goal-name">${escapeHtml(c.name)}</div><div class="muted small">${escapeHtml(c.bank)} • fecha ${c.closingDay} • vence ${c.dueDay}</div></div><strong>${fmt(c.invoice)}</strong></div><div class="goal-meta"><span>Limite ${fmt(c.limit)}</span><span>Disponível ${fmt(c.limit-c.invoice)}</span></div></div>`).join('')}<div class="card"><div class="section-title">Parcelas futuras</div>${data.installments.map(i=>`<div class="tx"><div class="tx-icon">▣</div><div><div class="tx-title">${escapeHtml(i.description)}</div><div class="tx-sub">${brDate(i.dueDate)} • ${i.installmentNo}/${i.installments}</div></div><div><div class="tx-amount">${fmt(i.amount)}</div><div class="tx-time ${i.paid?'income':''}">${i.paid?'Pago':'Aberto'}</div></div></div>`).join('')||'<div class="empty">Sem parcelas futuras.</div>'}</div>`}
function openCardForm(){openModal(`<div class="sheet-handle"></div><div class="sheet-title">Novo cartão</div><label>Nome</label><input id="cardName" class="field"/><label>Banco</label><input id="cardBank" class="field"/><label>Limite</label><input id="cardLimit" class="field" inputmode="decimal"/><label>Fatura atual</label><input id="cardInvoice" class="field" inputmode="decimal"/><div class="sheet-row"><div><label>Fecha dia</label><input id="cardClose" class="field" inputmode="numeric"/></div><div><label>Vence dia</label><input id="cardDue" class="field" inputmode="numeric"/></div></div><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveCard()">Salvar</button></div>`)}
function saveCard(){const name=$('#cardName').value.trim();if(!name)return showToast('Informe o nome');data.cards.push({id:uid(),name,bank:$('#cardBank').value,limit:num($('#cardLimit').value),invoice:num($('#cardInvoice').value),closingDay:parseInt($('#cardClose').value||0),dueDay:parseInt($('#cardDue').value||0)});queueChange('card','Cartão adicionado');closeModal();render()}
function openCardPurchase(){if(!data.cards.length)return showToast('Cadastre um cartão primeiro');openModal(`<div class="sheet-handle"></div><div class="sheet-title">Nova compra parcelada</div><label>Cartão</label><select id="buyCard" class="field">${data.cards.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select><label>Descrição</label><input id="buyDesc" class="field"/><label>Valor total</label><input id="buyTotal" class="field" inputmode="decimal"/><label>Número de parcelas</label><input id="buyN" class="field" inputmode="numeric" value="1"/><label>Primeiro vencimento</label><input id="buyDate" type="date" class="field" value="${isoToday()}"/><div class="sheet-footer"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveCardPurchase()">Gerar parcelas</button></div>`)}
function addMonthsIso(iso,m){const d=new Date(iso+'T12:00:00');d.setMonth(d.getMonth()+m);return d.toISOString().slice(0,10)}
function saveCardPurchase(){const card=data.cards.find(c=>c.id===$('#buyCard').value),total=num($('#buyTotal').value),n=Math.max(1,parseInt($('#buyN').value||1)),desc=$('#buyDesc').value.trim();if(!total||!desc)return showToast('Informe descrição e valor');data.cardPurchases??=[];const purchaseId=uid(),firstDue=$('#buyDate').value;data.cardPurchases.push({id:purchaseId,cardId:card.id,purchaseDate:isoToday(),description:desc,total,installments:n,firstDueDate:firstDue,notes:''});const cents=Math.round(total*100),base=Math.floor(cents/n),rem=cents-base*n;for(let k=0;k<n;k++){const c=(base+(k<rem?1:0))/100;data.installments.push({id:uid(),purchaseId,cardId:card.id,cardName:card.name,description:desc,installmentNo:k+1,installments:n,amount:c,dueDate:addMonthsIso(firstDue,k),paid:false,paidAt:''})}card.invoice+=total;queueChange('card_purchase',`${desc} ${n}x`);closeModal();render()}

function calculator(){return `${sectionHead('Calculadoras','')}<div class="segment" id="calcSeg"><button class="active" data-calc="simple">Simples</button><button data-calc="complete">Completa</button></div><div id="calcBody">${simpleCalcForm()}</div>`}
function simpleCalcForm(){return `<div class="card form-card"><div class="section-title">Quando consigo comprar?</div><label>O que você quer comprar?</label><input id="scName" class="field" placeholder="Ex.: Monitor"/><label>Preço à vista / meta</label><input id="scTarget" class="field" inputmode="decimal"/><label>Quanto você já tem?</label><input id="scInitial" class="field" inputmode="decimal" value="0"/><label>Quanto consegue guardar?</label><input id="scContribution" class="field" inputmode="decimal"/><label>Frequência</label><select id="scFreq" class="field"><option>Semanal</option><option>Mensal</option><option>Anual</option></select><label>Rentabilidade ao ano (%)</label><input id="scRate" class="field" inputmode="decimal" value="0"/><button class="primary" onclick="runSimpleCalc()">Calcular quando consigo comprar</button></div><div id="calcResult"></div>`}
function completeCalcForm(){return `<div class="card form-card"><div class="section-title">Planejamento completo</div><label>Aporte inicial</label><input id="ccInitial" class="field" inputmode="decimal" value="0"/><label>Aporte mensal</label><input id="ccMonthly" class="field" inputmode="decimal"/><label>Rentabilidade anual (%)</label><input id="ccRate" class="field" inputmode="decimal" value="10"/><label>Prazo (anos)</label><input id="ccYears" class="field" inputmode="numeric" value="10"/><label>13º investido por ano</label><input id="cc13" class="field" inputmode="decimal" value="0"/><label>PLR investida por ano</label><input id="ccPlr" class="field" inputmode="decimal" value="0"/><label>Aporte extra anual</label><input id="ccExtra" class="field" inputmode="decimal" value="0"/><label>Inflação anual (%)</label><input id="ccInflation" class="field" inputmode="decimal" value="4.5"/><label>Meta de patrimônio</label><input id="ccTarget" class="field" inputmode="decimal" value="0"/><button class="primary" onclick="runCompleteCalc()">Calcular projeção</button></div><div id="calcResult"></div>`}
function bindCalculator(){document.querySelectorAll('#calcSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#calcSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#calcBody').innerHTML=b.dataset.calc==='simple'?simpleCalcForm():completeCalcForm()})}
function runSimpleCalc(){const target=num($('#scTarget').value),initial=num($('#scInitial').value),contrib=num($('#scContribution').value),annual=num($('#scRate').value)/100,freq=$('#scFreq').value;if(!target||!contrib)return showToast('Informe meta e aporte');const perYear=freq==='Semanal'?52:freq==='Mensal'?12:1,rate=Math.pow(1+annual,1/perYear)-1;let bal=initial,steps=0;while(bal<target&&steps<20000){bal*=1+rate;bal+=contrib;steps++}const unit=freq==='Semanal'?'semanas':freq==='Mensal'?'meses':'anos';const months=freq==='Semanal'?steps*12/52:freq==='Mensal'?steps:steps*12;$('#calcResult').innerHTML=`<div class="card"><div class="section-title">Resultado</div><div style="font-size:34px;font-weight:900;color:var(--blue)">${steps} ${unit}</div><div class="muted">aproximadamente ${months.toFixed(1).replace('.',',')} meses para atingir ${fmt(target)}</div><div class="detail-kpis" style="margin-top:12px"><div class="mini-kpi"><small>Meta</small><strong>${fmt(target)}</strong></div><div class="mini-kpi"><small>Aporte</small><strong>${fmt(contrib)}</strong></div><div class="mini-kpi"><small>Saldo final</small><strong>${fmt(bal)}</strong></div></div></div>`}
function runCompleteCalc(){let bal=num($('#ccInitial').value),monthly=num($('#ccMonthly').value),rate=num($('#ccRate').value)/100,years=Math.max(1,parseInt($('#ccYears').value||1)),extra=num($('#cc13').value)+num($('#ccPlr').value)+num($('#ccExtra').value),infl=num($('#ccInflation').value)/100,target=num($('#ccTarget').value),months=years*12,totalContrib=bal,hit=null;const rm=Math.pow(1+rate,1/12)-1;for(let m=1;m<=months;m++){bal*=1+rm;bal+=monthly;totalContrib+=monthly;if(m%12===0){bal+=extra;totalContrib+=extra}if(target&&!hit&&bal>=target)hit=m}const real=bal/Math.pow(1+infl,years);$('#calcResult').innerHTML=`<div class="card"><div class="section-title">Projeção</div><div style="font-size:32px;font-weight:900;color:var(--blue)">${fmt(bal)}</div><div class="detail-kpis" style="margin-top:12px"><div class="mini-kpi"><small>Total aportado</small><strong>${fmt(totalContrib)}</strong></div><div class="mini-kpi"><small>Rendimento</small><strong>${fmt(bal-totalContrib)}</strong></div><div class="mini-kpi"><small>Valor real</small><strong>${fmt(real)}</strong></div></div>${target?`<div class="card" style="margin-top:12px;margin-bottom:0">${hit?`Meta de ${fmt(target)} atingida em cerca de ${hit} meses.`:`Meta de ${fmt(target)} não atingida no prazo informado.`}</div>`:''}</div>`}

function health(){const h=healthSummary();return `${sectionHead('Saúde financeira','')}<div class="card"><div class="row-between"><div><div class="muted">Score financeiro</div><div style="font-size:44px;font-weight:900;color:${h.score>=75?'var(--green)':h.score>=50?'var(--yellow)':'var(--red)'}">${Math.round(h.score)}</div></div><span class="chip ${h.score>=75?'green':h.score>=50?'yellow':'blue'}">de 100</span></div></div><div class="grid-2"><div class="kpi green"><div class="kpi-label">Taxa de poupança</div><div class="kpi-value">${pct(h.saveRate)}</div></div><div class="kpi red"><div class="kpi-label">Comprometimento</div><div class="kpi-value">${pct(h.debtCommit)}</div></div><div class="kpi"><div class="kpi-label">Reserva</div><div class="kpi-value">${h.reserveMonths.toFixed(1).replace('.',',')} meses</div></div><div class="kpi purple"><div class="kpi-label">Patrimônio</div><div class="kpi-value">${fmt(h.networth)}</div></div></div><div class="card"><div class="section-title">Leitura rápida</div><div class="info-list"><div class="info-row"><span>Reserva de emergência</span><strong>${h.reserveMonths>=6?'Boa':'Construindo'}</strong></div><div class="info-row"><span>Dívidas / renda</span><strong>${h.debtCommit<=20?'Controlado':'Atenção'}</strong></div><div class="info-row"><span>Taxa de poupança</span><strong>${h.saveRate>=20?'Boa':'Pode melhorar'}</strong></div></div></div>`}

function reports(){const t=totals(),cats=Object.keys(data.budget).map(c=>[c,categorySpent(c)]).sort((a,b)=>b[1]-a[1]);return `${sectionHead('Relatórios','')}<div class="grid-2"><div class="kpi green"><div class="kpi-label">Receitas</div><div class="kpi-value">${fmt(t.income)}</div></div><div class="kpi red"><div class="kpi-label">Despesas</div><div class="kpi-value">${fmt(t.expense)}</div></div></div><div class="card"><div class="section-title">Gastos por categoria</div>${cats.map(([c,v])=>{const max=Math.max(1,cats[0]?.[1]||1);return `<div style="margin:12px 0"><div class="row-between"><strong>${escapeHtml(c)}</strong><span>${fmt(v)}</span></div><div class="progress blue" style="margin-top:5px"><div style="width:${v/max*100}%"></div></div></div>`}).join('')}</div><div class="card"><div class="section-title">Resumo patrimonial</div><div class="info-list"><div class="info-row"><span>Contas</span><strong>${fmt(t.accounts)}</strong></div><div class="info-row"><span>Investimentos</span><strong>${fmt(t.investments)}</strong></div><div class="info-row"><span>Dívidas</span><strong>${fmt(t.debts)}</strong></div><div class="info-row"><span>Patrimônio líquido</span><strong>${fmt(t.networth)}</strong></div></div></div>`}

function importPage(){return `${sectionHead('Importar Nubank','')}<div class="card"><div class="section-title">Importar arquivo CSV</div><div class="muted small">Aceita arquivos CSV simples com colunas Data, Descrição, Valor. Valores negativos entram como despesa e positivos como receita.</div><input id="nubankFile" type="file" accept=".csv,text/csv" class="field" style="margin-top:12px"/><button class="primary" onclick="previewNubank()">Ler arquivo</button></div><div id="importPreview"></div><div class="card"><div class="section-title">Arquivos importados</div>${data.importedFiles.map(x=>`<div class="info-row"><span>${escapeHtml(x.name)}</span><strong>${x.rows} lançamentos</strong></div>`).join('')||'<div class="muted small">Nenhum arquivo importado.</div>'}</div>`}
let pendingImport=[];
async function previewNubank(){const f=$('#nubankFile').files?.[0];if(!f)return showToast('Selecione um CSV');const txt=await f.text(),lines=txt.split(/\r?\n/).filter(Boolean);if(lines.length<2)return showToast('CSV vazio');const sep=lines[0].includes(';')?';':',';const head=lines[0].split(sep).map(x=>x.trim().toLowerCase());const di=head.findIndex(x=>x.includes('data')||x.includes('date')),xi=head.findIndex(x=>x.includes('descr')||x.includes('title')),vi=head.findIndex(x=>x.includes('valor')||x.includes('amount'));if(vi<0)return showToast('Coluna de valor não encontrada');pendingImport=lines.slice(1).map(row=>{const p=row.split(sep);const amount=num(p[vi]);let date=p[di]||isoToday();if(date.includes('/')){const[a,b,c]=date.split('/');date=`${c}-${b.padStart(2,'0')}-${a.padStart(2,'0')}`}return{id:uid(),date,time:'',type:amount<0?'expense':'income',amount:Math.abs(amount),category:'Importado Nubank',description:p[xi]||'Lançamento Nubank',account:'Nubank',icon:'NU'}}).filter(x=>x.amount);$('#importPreview').innerHTML=`<div class="card"><div class="section-title">Prévia</div><div class="muted small">${pendingImport.length} lançamentos encontrados.</div>${pendingImport.slice(0,5).map(x=>`<div class="info-row"><span>${escapeHtml(x.description)}</span><strong>${fmt(x.amount)}</strong></div>`).join('')}<button class="primary" onclick="confirmNubankImport('${escapeHtml(f.name)}')">Confirmar importação</button></div>`}
function confirmNubankImport(name){data.transactions.unshift(...pendingImport);data.importedFiles.unshift({id:uid(),name,rows:pendingImport.length,date:nowIso()});queueChange('import',`Importação ${name}`);pendingImport=[];showToast('Importação concluída');render()}

function settings(){return `${sectionHead('Configurações','')}<div class="card form-card"><label>Nome</label><input id="setName" class="field" value="${escapeHtml(data.settings.userName)}"/><label>Renda mensal</label><input id="setIncome" class="field" inputmode="decimal" value="${data.settings.monthlyIncome}"/><label>Base essencial mensal</label><input id="setEssential" class="field" inputmode="decimal" value="${data.settings.essentialBase}"/><button class="primary" onclick="saveSettings()">Salvar configurações</button></div><div class="card form-card"><div class="section-title">Google Drive</div><div class="muted small">Use um OAuth Client ID do tipo <strong>Aplicativo da Web</strong>, criado no mesmo projeto Google Cloud usado pelo programa Windows.</div><label>Google Web Client ID</label><input id="setGoogleClientId" class="field" value="${escapeHtml(state.meta.googleClientId||'')}" placeholder="000000000000-xxxx.apps.googleusercontent.com"/><button class="primary" onclick="saveGoogleClientId()">Salvar Client ID</button><div class="muted small" style="margin-top:10px">Para login direto no celular, esta PWA precisa estar hospedada em HTTPS. O endereço local http://192.168... continua funcionando para testar a interface.</div></div><div class="card"><div class="section-title">Dados e segurança</div><button class="secondary" style="width:100%;margin-bottom:8px" onclick="exportSyncPackage()">Exportar backup JSON</button><button class="secondary" style="width:100%;margin-bottom:8px" onclick="triggerImport()">Importar backup JSON</button><button class="secondary danger" style="width:100%" onclick="store.reset()">Restaurar dados de demonstração</button></div>`}
function saveSettings(){data.settings.userName=$('#setName').value.trim()||'Matheus';data.settings.monthlyIncome=num($('#setIncome').value);data.settings.essentialBase=num($('#setEssential').value);queueChange('settings','Configurações atualizadas');showToast('Configurações salvas');render()}
function saveGoogleClientId(){const v=$('#setGoogleClientId').value.trim();state.meta.googleClientId=v;save();showToast(v?'Client ID salvo':'Client ID removido');render()}

function syncCenter(){const httpsOk=location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1';return `<div class="card"><div class="row-between"><div class="section-title">Central de sincronização</div><span class="chip ${state.meta.syncConnected?'green':'yellow'}">${state.meta.syncConnected?'Drive conectado':'Configurar'}</span></div><div class="status-grid"><div class="status-box"><div class="muted small">Dispositivo</div><strong>${state.meta.deviceId}</strong></div><div class="status-box"><div class="muted small">Revisão</div><strong>${state.meta.driveLastRevision||0}</strong></div><div class="status-box"><div class="muted small">Última sincronização</div><strong>${state.meta.lastSyncAt?new Date(state.meta.lastSyncAt).toLocaleString('pt-BR'):'Ainda não'}</strong></div><div class="status-box"><div class="muted small">Alterações locais</div><strong>${state.meta.pendingChanges||0}</strong></div></div>${!httpsOk?'<div class="card" style="background:var(--yellowSoft);margin-top:12px;margin-bottom:0"><strong style="color:var(--yellow)">HTTPS necessário para login Google no celular</strong><div class="muted small" style="margin-top:4px">Hospede esta PWA no GitHub Pages ou outro endereço HTTPS. O acesso por IP local continua disponível apenas para testes.</div></div>':''}<div class="actions-row" style="margin-top:12px"><button class="secondary" onclick="connectGoogleDriveMobile()">Conectar Google Drive</button><button class="secondary" onclick="googleDriveSyncMobile('auto')">Sincronizar agora</button></div><div class="actions-row" style="margin-top:10px"><button class="secondary" onclick="googleDriveSyncMobile('download')">Baixar do Drive</button><button class="secondary" onclick="googleDriveSyncMobile('upload')">Enviar celular</button></div></div>`}
function syncPage(){return `${sectionHead('Google Drive','')}${syncCenter()}<div class="card"><div class="section-title">Fila de alterações locais</div>${state.meta.changeQueue.slice(0,12).map(q=>`<div class="tx"><div class="tx-icon">↻</div><div><div class="tx-title">${escapeHtml(q.summary)}</div><div class="tx-sub">${new Date(q.at).toLocaleString('pt-BR')}</div></div><span class="chip yellow">Pendente</span></div>`).join('')||'<div class="empty">Nenhuma alteração pendente.</div>'}</div>`}

const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
const DRIVE_FOLDER='Controle Financeiro';
const DRIVE_FILE='controle_financeiro_sync.json';
let googleAccessToken='';
function stableObject(v){if(Array.isArray(v))return v.map(stableObject);if(v&&typeof v==='object'){const o={};Object.keys(v).sort().forEach(k=>o[k]=stableObject(v[k]));return o}return v}
async function hashData(v){const raw=new TextEncoder().encode(JSON.stringify(stableObject(v)));const buf=await crypto.subtle.digest('SHA-256',raw);return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cloudPayload(revision){return {schema:'controle-financeiro-sync',schemaVersion:1,revision:Number(revision||0),updatedAt:nowIso(),updatedBy:state.meta.deviceId,meta:{app:'Controle Financeiro Mobile',mobileVersion:'0.4.1'},data}}
function requireSecureGoogle(){if(!(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))throw new Error('O login Google no navegador exige HTTPS. Publique a PWA no GitHub Pages e use o endereço HTTPS como origem autorizada no Google Cloud.')}
function requestGoogleToken(){return new Promise((resolve,reject)=>{try{requireSecureGoogle();if(!state.meta.googleClientId)throw new Error('Informe o Google Web Client ID em Configurações.');if(!window.google?.accounts?.oauth2)throw new Error('Biblioteca do Google ainda não carregou. Aguarde alguns segundos e tente novamente.');const client=google.accounts.oauth2.initTokenClient({client_id:state.meta.googleClientId,scope:DRIVE_SCOPE,prompt:'consent',callback:r=>{if(r.error)return reject(new Error(r.error));googleAccessToken=r.access_token;state.meta.syncConnected=true;save();resolve(r.access_token)}});client.requestAccessToken({prompt:googleAccessToken?'':'consent'})}catch(e){reject(e)}})}
async function driveFetch(url,opts={}){if(!googleAccessToken)await requestGoogleToken();const headers={...(opts.headers||{}),Authorization:`Bearer ${googleAccessToken}`};const res=await fetch(url,{...opts,headers});if(res.status===401){googleAccessToken='';await requestGoogleToken();return driveFetch(url,opts)}if(!res.ok){const t=await res.text();throw new Error(`Google Drive ${res.status}: ${t.slice(0,240)}`)}return res}
function qEscape(s){return s.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
async function driveList(q){const u='https://www.googleapis.com/drive/v3/files?spaces=drive&fields=files(id,name,modifiedTime,size,md5Checksum)&q='+encodeURIComponent(q);return (await (await driveFetch(u)).json()).files||[]}
async function findOrCreateDriveFolder(){if(state.meta.driveFolderId)return state.meta.driveFolderId;let files=await driveList(`name='${qEscape(DRIVE_FOLDER)}' and mimeType='application/vnd.google-apps.folder' and trashed=false`);if(files[0]){state.meta.driveFolderId=files[0].id;save();return files[0].id}const res=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:DRIVE_FOLDER,mimeType:'application/vnd.google-apps.folder',appProperties:{cf_role:'root'}})});const obj=await res.json();state.meta.driveFolderId=obj.id;save();return obj.id}
async function findDriveSyncFile(folderId){if(state.meta.driveFileId)return {id:state.meta.driveFileId};const files=await driveList(`name='${qEscape(DRIVE_FILE)}' and '${folderId}' in parents and trashed=false`);if(files[0]){state.meta.driveFileId=files[0].id;save();return files[0]}return null}
async function downloadDrivePayload(){const folder=await findOrCreateDriveFolder();const f=await findDriveSyncFile(folder);if(!f)return {payload:null,file:null};const res=await driveFetch(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);return {payload:await res.json(),file:f}}
async function uploadDrivePayload(payload){const folder=await findOrCreateDriveFolder();let f=await findDriveSyncFile(folder);if(!f){const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:DRIVE_FILE,parents:[folder],mimeType:'application/json',appProperties:{cf_role:'sync',schema:'1'}})});f=await r.json();state.meta.driveFileId=f.id;save()}await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${f.id}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return f.id}
async function connectGoogleDriveMobile(){try{await requestGoogleToken();await findOrCreateDriveFolder();showToast('Google Drive conectado');render()}catch(e){alert(e.message)}}
async function checkpointDrive(payload){state.meta.driveLastRevision=Number(payload.revision||0);state.meta.driveLastHash=await hashData(payload.data||{});state.meta.lastSyncAt=nowIso();state.meta.changeQueue=[];state.meta.pendingChanges=0;state.meta.syncConnected=true;save()}
async function googleDriveSyncMobile(direction='auto'){try{await requestGoogleToken();showToast('Sincronizando com o Google Drive...');const local=cloudPayload(state.meta.driveLastRevision||0),localHash=await hashData(local.data),remoteInfo=await downloadDrivePayload(),remote=remoteInfo.payload,lastRev=Number(state.meta.driveLastRevision||0),lastHash=state.meta.driveLastHash||'';if(!remote){local.revision=Math.max(1,lastRev+1);await uploadDrivePayload(local);await checkpointDrive(local);showToast('Primeira versão enviada ao Drive');return render()}const remoteRev=Number(remote.revision||0),localChanged=lastHash?localHash!==lastHash:(state.meta.changeQueue.length>0),remoteChanged=lastRev?remoteRev!==lastRev:true;if(direction==='download'||(!lastRev&&direction==='auto')){if(direction==='download'&&!confirm('Baixar os dados do Google Drive e substituir os dados locais deste celular?'))return;state.data=ensureData(remote.data||{});data=state.data;await checkpointDrive(remote);showToast('Dados do Drive aplicados no celular');return render()}if(direction==='upload'){if(!confirm('Enviar os dados deste celular e substituir a versão atual do Google Drive?'))return;local.revision=Math.max(remoteRev,lastRev)+1;await uploadDrivePayload(local);await checkpointDrive(local);showToast('Dados do celular enviados ao Drive');return render()}if(remoteChanged&&localChanged)throw new Error('CONFLITO: o Google Drive e este celular foram alterados desde a última sincronização. Use Baixar do Drive ou Enviar celular depois de decidir qual versão deve prevalecer.');if(remoteChanged){state.data=ensureData(remote.data||{});data=state.data;await checkpointDrive(remote);showToast('Atualização recebida do Drive');return render()}if(localChanged){local.revision=remoteRev+1;await uploadDrivePayload(local);await checkpointDrive(local);showToast('Alterações enviadas ao Drive');return render()}showToast('Já está tudo sincronizado');state.meta.lastSyncAt=nowIso();save();render()}catch(e){alert(e.message)}}

function more(){return `${sectionHead('Mais','')}<div class="card profile"><div class="avatar">MH</div><div><div class="goal-name">${escapeHtml(data.settings.userName)}</div><div class="muted small">Controle Financeiro Mobile v0.4.1</div></div></div><div class="card menu-card">${[
['◔','Orçamento','budget'],['↻','Contas fixas','recurring'],['▤','Dívidas e Parcelas','debts'],['▣','Cartões de crédito','cards'],['▥','Investimentos','investments'],['⌁','Calculadoras','calculator'],['♥','Saúde financeira','health'],['▥','Relatórios','reports'],['NU','Importar Nubank','import']].map(x=>`<div class="menu-row" onclick="nav('${x[2]}')"><div class="menu-icon">${x[0]}</div><div>${x[1]}</div><div class="chev">›</div></div>`).join('')}</div><div class="card menu-card"><div class="menu-row" onclick="nav('sync')"><div class="menu-icon">▲</div><div>Google Drive <div class="small income">● estrutura preparada</div></div><div class="chev">›</div></div><div class="menu-row" onclick="nav('settings')"><div class="menu-icon">⚙</div><div>Configurações e Backup</div><div class="chev">›</div></div></div>`}

function bindCalculator(){document.querySelectorAll('#calcSeg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#calcSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#calcBody').innerHTML=b.dataset.calc==='simple'?simpleCalcForm():completeCalcForm()})}
function exportSyncPackage(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`controle_financeiro_mobile_backup_${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();showToast('Backup exportado')}
function triggerImport(){importFile.value='';importFile.click()}
importFile.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const incoming=migrate(JSON.parse(await f.text()));state=incoming;data=state.data;save();showToast('Backup importado');render()}catch{showToast('Arquivo inválido')}})

function render(){const route=currentRoute;const map={home,transactions,newtx:newTransaction,goals,goaldetail:goalDetail,networth,investments,budget,recurring,debts,cards,calculator,health,reports,import:importPage,settings,sync:syncPage,more};view.innerHTML=(map[route]||more)();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route||(route==='goaldetail'&&b.dataset.route==='goals')||(route==='newtx'&&b.dataset.route==='transactions')||(route==='investments'&&b.dataset.route==='networth')));if(route==='transactions')bindTransactions();if(route==='newtx')bindTypeSeg();if(route==='goals')bindGoals();if(route==='calculator')bindCalculator();window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.route));
window.addEventListener('hashchange',()=>{const parts=location.hash.split('/');if(parts[1]){currentRoute=parts[1];render()}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=$('#installBtn');b.hidden=false;b.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;b.hidden=true;deferredPrompt=null}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
